//! LYTH IR to PTX text.
//!
//! No dependency on CUDA, on purpose: emission stays testable on a machine with no GPU, and
//! validating the result with `ptxas` is a separate, optional step.
//!
//! One element per thread, bounds-checked. There is no grid-stride loop in v1, so nothing here
//! is tuned for occupancy and no performance claim comes out of it. **This back end exists to
//! be correct and to move exactly the bytes the front end derived.**

use std::fmt::Write as _;

use lyth_lang::ast::Ty;
use lyth_lang::ir::{KernelIr, Op, RegId};
use lyth_lang::BinOp;

/// The PTX ISA version each target first became legal in.
///
/// This is not a constant, because it is a property of the machine. `.version 8.5` with
/// `.target sm_120` is rejected outright by ptxas — found by generating exactly that and
/// reading the JIT log — so the version has to follow the target the machine file names.
/// A too-low version fails loudly; a too-high one fails on an older driver. Both are worse
/// than a table that says what is known.
const TARGET_ISA: &[(&str, &str)] = &[
    ("sm_120", "8.7"),
    ("sm_100", "8.7"),
    ("sm_90", "7.8"),
    ("sm_89", "7.8"),
    ("sm_86", "7.1"),
    ("sm_80", "7.0"),
    ("sm_75", "6.3"),
];

fn isa_for(arch: &str) -> Result<&'static str, EmitError> {
    TARGET_ISA
        .iter()
        .find(|(t, _)| *t == arch)
        .map(|(_, v)| *v)
        .ok_or_else(|| {
            let known: Vec<&str> = TARGET_ISA.iter().map(|(t, _)| *t).collect();
            EmitError::UnknownTarget(arch.to_string(), known.join(", "))
        })
}

#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error(
        "kernel `{0}` has no parameter that bounds the index space; add an `n: u32` parameter"
    )]
    NoBound(String),
    #[error("kernel `{0}` drains nothing, so it computes a value and discards it")]
    NoDrain(String),
    #[error(
        "no PTX ISA version is recorded for target `{0}`. Known: {1}. Add it to TARGET_ISA rather than guessing: `.version` too low is rejected by ptxas, too high by an older driver."
    )]
    UnknownTarget(String, String),
    #[error("{0}")]
    Message(String),
}

/// The generated module, and the facts a caller needs to launch it.
#[derive(Debug, Clone, PartialEq)]
pub struct Module {
    pub ptx: String,
    pub entry: String,
    /// Launch parameters in declaration order, so the host passes them in the right order.
    pub params: Vec<(String, Ty)>,
    /// The `u32` parameter that bounds the element index.
    pub bound: String,
    pub arch: String,
}

/// Emit PTX for one lowered kernel.
///
/// `arch` is the machine's target string, `sm_120` and so on. It comes from the machine file
/// rather than from a flag: ADR-0001 makes the machine a value, and `-arch` is exactly the
/// kind of flag that rots.
pub fn emit(ir: &KernelIr, arch: &str) -> Result<Module, EmitError> {
    // The first u32 parameter bounds the index space. v1 is one-dimensional, so one bound.
    let bound = ir
        .params
        .iter()
        .find(|p| p.ty == Ty::U32)
        .map(|p| p.name.clone())
        .ok_or_else(|| EmitError::NoBound(ir.name.clone()))?;
    if ir.drains.is_empty() {
        return Err(EmitError::NoDrain(ir.name.clone()));
    }

    // PTX declares its virtual register banks up front, so the body is emitted first and the
    // header is written once the counts are known.
    let mut e = Emitter {
        n_pred: 0,
        n_f32: 0,
        n_b32: 0,
        n_b64: 0,
    };
    let mut body = String::new();
    e.body(ir, &bound, &mut body)?;

    let mut ptx = String::new();
    let _ = writeln!(ptx, "//");
    let _ = writeln!(ptx, "// Generated by LYTH. Do not edit.");
    let _ = writeln!(ptx, "//   kernel    {}", ir.name);
    let _ = writeln!(ptx, "//   machine   {}", ir.machine);
    let _ = writeln!(
        ptx,
        "//   derived   {:.6} flop/byte = {} flop / {} byte per element",
        ir.cost.intensity, ir.cost.flops_per_element, ir.cost.bytes_per_element
    );
    let _ = writeln!(
        ptx,
        "//   traffic   {} read + {} written, per element, at {}",
        ir.cost.read_bytes_per_element,
        ir.cost.write_bytes_per_element,
        ir.cost.level.name()
    );
    let _ = writeln!(ptx, "//");
    let _ = writeln!(ptx, ".version {}", isa_for(arch)?);
    let _ = writeln!(ptx, ".target {arch}");
    let _ = writeln!(ptx, ".address_size 64");
    let _ = writeln!(ptx);
    let _ = writeln!(ptx, ".visible .entry {}(", ir.name);
    let params: Vec<String> = ir
        .params
        .iter()
        .map(|p| {
            let kind = match p.ty {
                Ty::U32 => ".u32",
                Ty::F32 => ".f32",
                Ty::BufF32 => ".u64",
            };
            format!("    .param {kind} {}_{}", ir.name, p.name)
        })
        .collect();
    let _ = writeln!(ptx, "{}", params.join(",\n"));
    let _ = writeln!(ptx, ")");
    let _ = writeln!(ptx, "{{");
    if e.n_pred > 0 {
        let _ = writeln!(ptx, "    .reg .pred  %p<{}>;", e.n_pred + 1);
    }
    if e.n_f32 > 0 {
        let _ = writeln!(ptx, "    .reg .f32   %f<{}>;", e.n_f32 + 1);
    }
    if e.n_b32 > 0 {
        let _ = writeln!(ptx, "    .reg .b32   %r<{}>;", e.n_b32 + 1);
    }
    if e.n_b64 > 0 {
        let _ = writeln!(ptx, "    .reg .b64   %rd<{}>;", e.n_b64 + 1);
    }
    let _ = writeln!(ptx);
    ptx.push_str(&body);
    let _ = writeln!(ptx, "}}");

    Ok(Module {
        ptx,
        entry: ir.name.clone(),
        params: ir.params.iter().map(|p| (p.name.clone(), p.ty)).collect(),
        bound,
        arch: arch.to_string(),
    })
}

struct Emitter {
    n_pred: u32,
    n_f32: u32,
    n_b32: u32,
    n_b64: u32,
}

fn line(o: &mut String, s: &str) {
    let _ = writeln!(o, "    {s}");
}

impl Emitter {
    fn pred(&mut self) -> String {
        self.n_pred += 1;
        format!("%p{}", self.n_pred)
    }

    fn f32(&mut self) -> String {
        self.n_f32 += 1;
        format!("%f{}", self.n_f32)
    }

    fn b32(&mut self) -> String {
        self.n_b32 += 1;
        format!("%r{}", self.n_b32)
    }

    fn b64(&mut self) -> String {
        self.n_b64 += 1;
        format!("%rd{}", self.n_b64)
    }

    fn body(&mut self, ir: &KernelIr, bound: &str, out: &mut String) -> Result<(), EmitError> {
        let k = &ir.name;

        // --- parameters into registers ----------------------------------------------
        let r_bound = self.b32();
        line(out, &format!("ld.param.u32 {r_bound}, [{k}_{bound}];"));

        let mut scalars: Vec<(String, String)> = Vec::new();
        for p in &ir.params {
            if p.ty == Ty::F32 {
                let r = self.f32();
                line(out, &format!("ld.param.f32 {r}, [{k}_{}];", p.name));
                scalars.push((p.name.clone(), r));
            }
        }
        let mut buffers: Vec<(String, String)> = Vec::new();
        for p in &ir.params {
            if p.ty == Ty::BufF32 {
                let raw = self.b64();
                let glob = self.b64();
                line(out, &format!("ld.param.u64 {raw}, [{k}_{}];", p.name));
                // Generic to global: a generic address pays an extra translation on every
                // access, and every buffer here is global by construction.
                line(out, &format!("cvta.to.global.u64 {glob}, {raw};"));
                buffers.push((p.name.clone(), glob));
            }
        }

        // --- index, and the bounds check ---------------------------------------------
        let ctaid = self.b32();
        let ntid = self.b32();
        let tid = self.b32();
        let idx = self.b32();
        line(out, &format!("mov.u32 {ctaid}, %ctaid.x;"));
        line(out, &format!("mov.u32 {ntid}, %ntid.x;"));
        line(out, &format!("mov.u32 {tid}, %tid.x;"));
        line(out, &format!("mad.lo.s32 {idx}, {ctaid}, {ntid}, {tid};"));
        let p = self.pred();
        line(out, &format!("setp.ge.u32 {p}, {idx}, {r_bound};"));
        line(out, &format!("@{p} bra $L_done_{k};"));

        // --- one element address per buffer ------------------------------------------
        let off = self.b64();
        line(out, &format!("mul.wide.u32 {off}, {idx}, 4;"));
        let mut addrs: Vec<(String, String)> = Vec::new();
        for (name, base) in &buffers {
            let a = self.b64();
            line(out, &format!("add.s64 {a}, {base}, {off};"));
            addrs.push((name.clone(), a));
        }
        let addr_of = |name: &str| -> String {
            addrs
                .iter()
                .find(|(n, _)| n == name)
                .map(|(_, a)| a.clone())
                .expect("every buffer parameter got an address")
        };

        // --- the body -----------------------------------------------------------------
        let mut regs: Vec<(RegId, String)> = Vec::new();
        fn get(regs: &[(RegId, String)], id: RegId) -> String {
            regs.iter()
                .find(|(i, _)| *i == id)
                .map(|(_, r)| r.clone())
                .expect("SSA: every use follows its definition")
        }
        for op in &ir.ops {
            match op {
                Op::Load { dst, buffer } => {
                    let r = self.f32();
                    line(out, &format!("ld.global.f32 {r}, [{}];", addr_of(buffer)));
                    regs.push((*dst, r));
                }
                Op::Param { dst, name } => {
                    let r = scalars
                        .iter()
                        .find(|(n, _)| n == name)
                        .map(|(_, r)| r.clone())
                        .ok_or_else(|| {
                            EmitError::Message(format!("no register holds scalar `{name}`"))
                        })?;
                    regs.push((*dst, r));
                }
                Op::Const { dst, value } => {
                    let r = self.f32();
                    line(out, &format!("mov.f32 {r}, {};", hex_f32(*value as f32)));
                    regs.push((*dst, r));
                }
                Op::Bin { dst, op, lhs, rhs } => {
                    let r = self.f32();
                    // `.rn` is round-to-nearest-even, the IEEE default. Spelling it out means
                    // a later reader can see that no fast-math rounding was chosen quietly.
                    let mnemonic = match op {
                        BinOp::Add => "add.rn.f32",
                        BinOp::Sub => "sub.rn.f32",
                        BinOp::Mul => "mul.rn.f32",
                        BinOp::Div => "div.rn.f32",
                    };
                    line(
                        out,
                        &format!(
                            "{mnemonic} {r}, {}, {};",
                            get(&regs, *lhs),
                            get(&regs, *rhs)
                        ),
                    );
                    regs.push((*dst, r));
                }
                Op::Fma { dst, a, b, c } => {
                    let r = self.f32();
                    line(
                        out,
                        &format!(
                            "fma.rn.f32 {r}, {}, {}, {};",
                            get(&regs, *a),
                            get(&regs, *b),
                            get(&regs, *c)
                        ),
                    );
                    regs.push((*dst, r));
                }
                Op::Neg { dst, src } => {
                    let r = self.f32();
                    line(out, &format!("neg.f32 {r}, {};", get(&regs, *src)));
                    regs.push((*dst, r));
                }
            }
        }

        // --- drains --------------------------------------------------------------------
        for (buffer, src) in &ir.drains {
            line(
                out,
                &format!("st.global.f32 [{}], {};", addr_of(buffer), get(&regs, *src)),
            );
        }

        let _ = writeln!(out, "$L_done_{k}:");
        line(out, "ret;");
        Ok(())
    }
}

/// PTX writes float immediates as a hex bit pattern, which is exact. A decimal literal would
/// be re-parsed by `ptxas` and could land on a different value than the one the front end
/// folded.
fn hex_f32(v: f32) -> String {
    format!("0f{:08X}", v.to_bits())
}

#[cfg(test)]
mod tests {
    use super::*;
    use lyth_lang::{ir::lower, parse::parse};

    const SAXPY: &str = "\
machine sm_120

kernel saxpy(n: u32, a: f32, x: [f32], y: [f32])
    intensity 0.1667

    stream x : dram -> reg
    stream y : dram -> reg, drain

    at reg:
        y = a * x + y
";

    fn saxpy_ptx() -> Module {
        let u = parse(SAXPY).unwrap();
        let ir = lower(&u, &u.kernels[0]).unwrap();
        emit(&ir, "sm_120").unwrap()
    }

    #[test]
    fn an_unknown_target_is_refused_and_lists_the_known_ones() {
        let u = parse(SAXPY).unwrap();
        let ir = lower(&u, &u.kernels[0]).unwrap();
        let e = emit(&ir, "sm_999").unwrap_err();
        assert!(e.to_string().contains("sm_120"), "{e}");
    }

    #[test]
    fn the_isa_version_follows_the_target_rather_than_being_fixed() {
        // Found by generating `.version 8.5` with `.target sm_120` and having ptxas reject it.
        assert_eq!(isa_for("sm_120").unwrap(), "8.7");
        assert_eq!(isa_for("sm_80").unwrap(), "7.0");
    }

    #[test]
    fn the_module_has_the_shape_ptxas_needs() {
        let m = saxpy_ptx();
        assert!(m.ptx.contains(".version 8.7"));
        assert!(m.ptx.contains(".target sm_120"));
        assert!(m.ptx.contains(".address_size 64"));
        assert!(m.ptx.contains(".visible .entry saxpy("));
        assert!(m.ptx.trim_end().ends_with('}'), "{}", m.ptx);
    }

    #[test]
    fn one_fma_and_no_separate_multiply() {
        let m = saxpy_ptx();
        assert_eq!(m.ptx.matches("fma.rn.f32").count(), 1, "{}", m.ptx);
        assert_eq!(m.ptx.matches("mul.rn.f32").count(), 0, "{}", m.ptx);
    }

    #[test]
    fn the_bytes_it_moves_are_the_bytes_the_front_end_derived() {
        let m = saxpy_ptx();
        // Two 4-byte loads and one 4-byte store: exactly the 8 read + 4 written that `Cost`
        // claims. If these two ever disagree, the derived intensity is fiction.
        assert_eq!(m.ptx.matches("ld.global.f32").count(), 2, "{}", m.ptx);
        assert_eq!(m.ptx.matches("st.global.f32").count(), 1, "{}", m.ptx);
    }

    #[test]
    fn every_thread_is_bounds_checked() {
        let m = saxpy_ptx();
        assert!(m.ptx.contains("setp.ge.u32"), "{}", m.ptx);
        assert!(m.ptx.contains("bra $L_done_saxpy"), "{}", m.ptx);
    }

    #[test]
    fn the_header_records_what_the_compiler_derived() {
        let m = saxpy_ptx();
        assert!(m.ptx.contains("0.166667 flop/byte"), "{}", m.ptx);
        assert!(m.ptx.contains("8 read + 4 written"), "{}", m.ptx);
    }

    #[test]
    fn float_constants_are_exact_bit_patterns() {
        assert_eq!(hex_f32(1.0), "0f3F800000");
        assert_eq!(hex_f32(0.0), "0f00000000");
        assert_eq!(hex_f32(-2.5), "0fC0200000");
    }

    #[test]
    fn a_kernel_with_no_bound_is_refused_rather_than_running_off_the_end() {
        let src = "machine sm_120\n\nkernel k(x: [f32], y: [f32])\n    stream x : dram -> reg\n    stream y : dram -> reg, drain\n    at reg:
        y = x\n";
        let u = parse(src).unwrap();
        let ir = lower(&u, &u.kernels[0]).unwrap();
        let e = emit(&ir, "sm_120").unwrap_err();
        assert!(e.to_string().contains("bounds the index space"), "{e}");
    }

    #[test]
    fn registers_are_declared_before_they_are_used() {
        let m = saxpy_ptx();
        let decl = m.ptx.find(".reg .f32").expect("an f32 bank");
        let first_use = m.ptx.find("ld.param.f32").expect("a parameter load");
        assert!(decl < first_use, "PTX declares its banks up front");
    }
}
