//! A Python module, generated from the manifest (ADR-0016).
//!
//! `ctypes` against the CUDA driver, so it imports on a bare interpreter: no `cupy`, no
//! `cuda-python`, no build step, nothing to `pip install`. The PTX is embedded, as in the
//! other two bindings, because a kernel that loads from disk can be out of step with the code
//! that launches it.
//!
//! **It does not allocate.** Rule 1 of ADR-0016 holds here more visibly than anywhere else:
//! the launcher takes device pointers as integers, which is exactly what
//! `torch.Tensor.data_ptr()` and `cupy.ndarray.data.ptr` already hand out. A binding that
//! allocated would force a caller to move data between its allocator and ours for no reason.
//! For a caller with neither library, the loaded driver is exposed as `cuda` so they can call
//! `cuMemAlloc` themselves.
//!
//! Python cannot express the aliasing rule the Rust binding gets from the borrow checker, and
//! does not pretend to: which buffers are written is in the docstring, as it is in the C header.

use crate::manifest::Manifest;

pub fn generate(m: &Manifest, ptx: &str, source: &str) -> String {
    let k = &m.kernel;

    let extents: Vec<&str> = m
        .params
        .iter()
        .filter(|p| p.is_extent)
        .map(|p| p.name.as_str())
        .collect();
    let extent_args = if extents.is_empty() {
        "n".to_string()
    } else {
        extents.join(", ")
    };

    let args: Vec<String> = m.params.iter().map(|p| p.name.clone()).collect();
    let written: Vec<&str> = m
        .params
        .iter()
        .filter(|p| p.written && p.ty == "buf_f32")
        .map(|p| p.name.as_str())
        .collect();

    // ctypes needs the exact width of each argument, since the driver reads the parameter
    // buffer by offset. A Python int passed as the wrong width silently shifts everything
    // after it.
    let ctypes: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.ty.as_str() {
            "u32" => format!("ctypes.c_uint32({})", p.name),
            "f32" => format!("ctypes.c_float({})", p.name),
            _ => format!("ctypes.c_uint64({})", p.name),
        })
        .collect();

    let mut o = String::new();
    let mut w = |l: &str| {
        o.push_str(l);
        o.push('\n');
    };

    w(&format!("# GENERATED BY LYTH from {source}. Do not edit."));
    w("#");
    w(&format!(
        "# Contract: {:.4} flop/byte derived on {}, {} flop and {} byte per element.",
        m.contract.derived_intensity,
        m.contract.machine,
        m.contract.flops_per_element,
        m.contract.bytes_per_element
    ));
    if m.contract.coalescence < 1.0 {
        w(&format!(
            "# Bus: {} + {} byte per element at L1->L2, coalescence {:.3}. Strided: {}.",
            m.contract.sector_read_per_element,
            m.contract.sector_write_per_element,
            m.contract.coalescence,
            m.contract.strided_buffers.join(", ")
        ));
    }
    w("");
    w("import ctypes");
    w("import sys");
    w("");
    w(&format!("KERNEL = \"{k}\""));
    w(&format!("MACHINE = \"{}\"", m.contract.machine));
    w(&format!("BLOCK = {}", m.launch.block));
    w(&format!("SHARED_BYTES = {}", m.launch.shared_bytes));
    w(&format!("MAX_GRID = {}", m.launch.max_grid));
    w("");
    w("# The cost model, so a caller can assert on it without a profiler.");
    w(&format!(
        "DERIVED_INTENSITY = {:?}",
        m.contract.derived_intensity
    ));
    w(&format!(
        "FLOPS_PER_ELEMENT = {:?}",
        m.contract.flops_per_element
    ));
    w(&format!(
        "BYTES_PER_ELEMENT = {:?}",
        m.contract.bytes_per_element
    ));
    w(&format!("COALESCENCE = {:?}", m.contract.coalescence));
    w("");
    w("PTX = (");
    for l in ptx.lines() {
        let escaped = l.replace('\\', "\\\\").replace('"', "\\\"");
        w(&format!("    \"{escaped}\\n\""));
    }
    w(")");
    w("");
    w("# The driver itself, exposed so a caller with neither cupy nor torch can allocate.");
    w("cuda = ctypes.WinDLL(\"nvcuda.dll\") if sys.platform == \"win32\" \\");
    w("    else ctypes.CDLL(\"libcuda.so.1\")");
    w("");
    w("");
    w("class CudaError(RuntimeError):");
    w("    pass");
    w("");
    w("");
    w("def check(name, code):");
    w("    \"\"\"Raise on a driver error, naming the call and the code.\"\"\"");
    w("    if code != 0:");
    w("        msg = ctypes.c_char_p()");
    w("        cuda.cuGetErrorString(code, ctypes.byref(msg))");
    w("        text = msg.value.decode() if msg.value else \"unknown\"");
    w("        raise CudaError(f\"{name} failed: {text} ({code})\")");
    w("");
    w("");
    w(&format!("def elements({extent_args}):"));
    w("    \"\"\"Elements the kernel walks. None if the extents overflow a 32-bit index.\"\"\"");
    if extents.len() <= 1 {
        w(&format!("    return {extent_args}"));
    } else {
        let prod = extents.join(" * ");
        w(&format!("    total = {prod}"));
        w("    return total if total <= 0xFFFFFFFF else None");
    }
    w("");
    w("");
    w(&format!("def grid({extent_args}):"));
    w("    \"\"\"Blocks the default launch uses: one element per thread, capped.\"\"\"");
    w(&format!("    total = elements({extent_args})"));
    w("    if total is None:");
    w("        return None");
    w("    return min(max(-(-total // BLOCK), 1), MAX_GRID)");
    w("");
    if let Some(p) = m.sized_by_grid() {
        w("");
        w(&format!("def {}_len({extent_args}):", p.name));
        w(&format!(
            "    \"\"\"Elements `{}` must hold: one per block, NOT one per element.\"\"\"",
            p.name
        ));
        w(&format!("    return grid({extent_args})"));
        w("");
    }
    w("");
    w("class Kernel:");
    w(&format!(
        "    \"\"\"The loaded module and its entry point.\n"
    ));
    w(&format!(
        "    Writes: {}. Every other buffer it only reads; Python cannot say so in the",
        if written.is_empty() {
            "nothing".to_string()
        } else {
            written.join(", ")
        }
    ));
    w("    signature, so it is said here.");
    w("    \"\"\"");
    w("");
    w("    def __init__(self):");
    w("        self.module = ctypes.c_void_p()");
    w("        self.fn = ctypes.c_void_p()");
    w("        check(\"cuModuleLoadData\", cuda.cuModuleLoadData(");
    w("            ctypes.byref(self.module), PTX.encode()))");
    w("        check(\"cuModuleGetFunction\", cuda.cuModuleGetFunction(");
    w("            ctypes.byref(self.fn), self.module, KERNEL.encode()))");
    w("");
    w(&format!(
        "    def launch(self, {}):",
        args.join(", ")
    ));
    w("        \"\"\"Launch at the compiler's default grid. Buffers are device pointers.\"\"\"");
    w(&format!("        g = grid({extent_args})"));
    w("        if g is None:");
    w("            raise ValueError(\"the extents overflow a 32-bit index\")");
    w(&format!(
        "        return self.launch_with(g, {})",
        args.join(", ")
    ));
    w("");
    w(&format!(
        "    def launch_with(self, grid, {}):",
        args.join(", ")
    ));
    w("        \"\"\"Launch at a grid of your choosing, for a sweep.\"\"\"");
    w(&format!("        values = [{}]", ctypes.join(", ")));
    w("        args = (ctypes.c_void_p * len(values))(");
    w("            *[ctypes.cast(ctypes.byref(v), ctypes.c_void_p) for v in values])");
    w("        check(\"cuLaunchKernel\", cuda.cuLaunchKernel(");
    w("            self.fn, grid, 1, 1, BLOCK, 1, 1, SHARED_BYTES, None, args, None))");
    o
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_launch_passes_each_argument_at_its_own_width() {
        // The driver reads the parameter buffer by offset, so a u32 passed as a Python int of
        // whatever width ctypes guesses would shift every argument after it. This is the one
        // place a Python binding can be silently, catastrophically wrong.
        let src = "machine sm_120\n\nkernel k(n: u32, a: f32, x: [f32; n], y: [f32; n])\n    stream x : dram -> reg\n    stream y : dram -> reg, drain\n    at reg:\n        y = a * x\n";
        let unit = lyth_lang::parse::parse(src).unwrap();
        let ir = lyth_lang::ir::lower(&unit, &unit.kernels[0]).unwrap();
        let m = Manifest::of(&ir, None, 256, 1 << 20, vec![]);
        let code = generate(&m, "// ptx", "k.lyth");
        assert!(code.contains("ctypes.c_uint32(n)"), "{code}");
        assert!(code.contains("ctypes.c_float(a)"), "{code}");
        assert!(code.contains("ctypes.c_uint64(x)"), "{code}");
        assert!(code.contains("ctypes.c_uint64(y)"), "{code}");
    }
}
