//! A C header, generated from the manifest (ADR-0016).
//!
//! One file, no build system, no library to link beyond the CUDA driver the caller already
//! links. Declarations by default; define `LYTH_<KERNEL>_IMPLEMENTATION` in exactly one
//! translation unit to get the bodies, which is the single-header convention and avoids
//! shipping a `.c` a caller has to add to their build.
//!
//! **The driver API, not the runtime API.** `cuModuleLoadData` and `cuLaunchKernel` take the
//! PTX this compiler emits and need no `nvcc`, no fat binary and no `__global__` function to
//! link against. A caller compiles the header with any C compiler and links `cuda`.
//!
//! What the Rust binding gets from the borrow checker -- an input that cannot alias an output
//! -- C cannot have, and the header does not pretend otherwise. `const CUdeviceptr` would look
//! like the guarantee without being it: `CUdeviceptr` is an integer handle, so the qualifier
//! applies to the handle and says nothing about the memory. The generated header states which
//! buffers are written in a comment and leaves the signature honest.

use crate::manifest::Manifest;

fn upper(s: &str) -> String {
    s.to_uppercase().replace(|c: char| !c.is_alphanumeric(), "_")
}

/// PTX as a run of C string literals, one per source line.
///
/// A single literal would need the whole module on one line and would break on any `"` in a
/// comment. One per line keeps the generated header readable, which matters: somebody will
/// open it to check what they are launching.
fn ptx_literal(ptx: &str) -> String {
    ptx.lines()
        .map(|l| {
            let escaped = l.replace('\\', "\\\\").replace('"', "\\\"");
            format!("    \"{escaped}\\n\"")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn generate(m: &Manifest, ptx: &str, source: &str) -> String {
    let guard = upper(&m.kernel);
    let k = &m.kernel;

    let extents: Vec<&str> = m
        .params
        .iter()
        .filter(|p| p.is_extent)
        .map(|p| p.name.as_str())
        .collect();
    let extent_args = if extents.is_empty() {
        "unsigned int n".to_string()
    } else {
        extents
            .iter()
            .map(|e| format!("unsigned int {e}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let extent_pass = if extents.is_empty() {
        "n".to_string()
    } else {
        extents.join(", ")
    };

    // No `const` on the buffers. `CUdeviceptr` is an integer handle, so `const CUdeviceptr`
    // qualifies the handle and says nothing whatever about the memory -- and it reads to a C
    // programmer as though it did. The Rust binding gets this from the borrow checker; C has
    // no way to express it, and a qualifier that looks like the guarantee without being it is
    // worse than none. Which buffers are written is stated in a comment instead.
    let sig: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.ty.as_str() {
            "u32" => format!("unsigned int {}", p.name),
            "f32" => format!("float {}", p.name),
            _ => format!("CUdeviceptr {}", p.name),
        })
        .collect();
    let written: Vec<&str> = m
        .params
        .iter()
        .filter(|p| p.written && p.ty == "buf_f32")
        .map(|p| p.name.as_str())
        .collect();
    let pass: Vec<String> = m.params.iter().map(|p| p.name.clone()).collect();

    let mut o = String::new();
    let mut w = |l: &str| {
        o.push_str(l);
        o.push('\n');
    };

    w(&format!("/* GENERATED BY LYTH from {source}. Do not edit. */"));
    w("/*");
    w(&format!(" * {}", crate::manifest::contract_line(&m.contract)));
    if m.contract.coalescence < 1.0 {
        w(&format!(
            " * Bus: {} + {} byte per element at L1->L2, coalescence {:.3}. Strided: {}.",
            m.contract.sector_read_per_element,
            m.contract.sector_write_per_element,
            m.contract.coalescence,
            m.contract.strided_buffers.join(", ")
        ));
    }
    w(" *");
    w(&format!(
        " * Define LYTH_{guard}_IMPLEMENTATION in one translation unit for the bodies."
    ));
    w(" * Needs the CUDA driver API only: compile with cuda.h and link cuda.");
    w(" */");
    w(&format!("#ifndef LYTH_{guard}_H"));
    w(&format!("#define LYTH_{guard}_H"));
    w("");
    w("#include <cuda.h>");
    w("");
    w("#ifdef __cplusplus");
    w("extern \"C\" {");
    w("#endif");
    w("");
    w(&format!("#define LYTH_{guard}_KERNEL \"{k}\""));
    w(&format!(
        "#define LYTH_{guard}_MACHINE \"{}\"",
        m.contract.machine
    ));
    w(&format!("#define LYTH_{guard}_BLOCK {}u", m.launch.block));
    w(&format!(
        "#define LYTH_{guard}_SHARED_BYTES {}u",
        m.launch.shared_bytes
    ));
    w(&format!(
        "#define LYTH_{guard}_MAX_GRID {}u",
        m.launch.max_grid
    ));
    w("");
    w("/* The cost model, so a caller can assert on it without a profiler. */");
    w(&format!(
        "#define LYTH_{guard}_DERIVED_INTENSITY {:?}",
        m.contract.derived_intensity
    ));
    w(&format!(
        "#define LYTH_{guard}_FLOPS_PER_ELEMENT {:?}",
        m.contract.flops_per_element.unwrap_or(0.0)
    ));
    w(&format!(
        "#define LYTH_{guard}_BYTES_PER_ELEMENT {:?}",
        m.contract.bytes_per_element.unwrap_or(0.0)
    ));
    w(&format!(
        "#define LYTH_{guard}_COALESCENCE {:?}",
        m.contract.coalescence
    ));
    w("");
    w("/* Elements the kernel walks. 0 means the extents overflow a 32-bit index. */");
    w(&format!("unsigned int lyth_{k}_elements({extent_args});"));
    w("/* Blocks the default launch uses: one element per thread, capped. 0 on overflow. */");
    w(&format!("unsigned int lyth_{k}_grid({extent_args});"));
    if let Some(p) = m.sized_by_grid() {
        w(&format!(
            "/* Elements `{}` must hold: one per block, NOT one per element. */",
            p.name
        ));
        w(&format!("unsigned int lyth_{k}_{}_len({extent_args});", p.name));
    }
    w(&format!(
        "/* The kernel writes: {}. Every other buffer it only reads. C cannot say this in the",
        if written.is_empty() {
            "nothing".to_string()
        } else {
            written.join(", ")
        }
    ));
    w("   signature -- CUdeviceptr is an integer handle -- so it is said here. */");
    w("/* Load the embedded PTX. The module must outlive every launch. */");
    w(&format!("CUresult lyth_{k}_load(CUmodule *module, CUfunction *fn);"));
    w(&format!(
        "CUresult lyth_{k}_launch({});",
        std::iter::once("CUfunction fn".to_string())
            .chain(sig.iter().cloned())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    w(&format!(
        "CUresult lyth_{k}_launch_with({});",
        ["CUfunction fn".to_string(), "unsigned int grid".to_string()]
            .into_iter()
            .chain(sig.iter().cloned())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    w("");
    w("#ifdef __cplusplus");
    w("}");
    w("#endif");
    w("");
    w(&format!("#ifdef LYTH_{guard}_IMPLEMENTATION"));
    w("");
    w(&format!("static const char lyth_{k}_ptx[] ="));
    w(&ptx_literal(ptx));
    w(";");
    w("");
    w(&format!("unsigned int lyth_{k}_elements({extent_args})"));
    w("{");
    if extents.len() <= 1 {
        w(&format!("    return {extent_pass};"));
    } else {
        let prod = extents
            .iter()
            .map(|e| format!("(unsigned long long){e}"))
            .collect::<Vec<_>>()
            .join(" * ");
        w(&format!("    unsigned long long total = {prod};"));
        w("    if (total > 0xFFFFFFFFull) return 0u;");
        w("    return (unsigned int)total;");
    }
    w("}");
    w("");
    w(&format!("unsigned int lyth_{k}_grid({extent_args})"));
    w("{");
    match &m.launch.grid {
        crate::manifest::GridRule::Elementwise {
            min_elements_per_thread,
            ..
        } => {
            // Not `n`: at rank 1 the extent is itself called `n`, and `unsigned int n = f(n)`
            // initialises the new local from its own indeterminate value. The compiler is
            // within its rights to do anything at all with that.
            w(&format!(
                "    unsigned int total = lyth_{k}_elements({extent_pass});"
            ));
            w("    unsigned int g;");
            w("    if (total == 0u) return 0u;");
            if *min_elements_per_thread > 1 {
                w("    /* Not one element per thread: this kernel reduces, and its block tree");
                w("       would then run once per element. The grid-stride loop walks the rest.");
                w("       The ceiling division is done in 64 bits: `total + per_block` overflows");
                w("       an unsigned int at a full extent. */");
                w(&format!(
                    "    {{ unsigned long long per_block = (unsigned long long)LYTH_{guard}_BLOCK * {min_elements_per_thread}ull;"
                ));
                w("      g = (unsigned int)(((unsigned long long)total + per_block - 1ull) / per_block); }");
            } else {
                w(&format!(
                    "    g = (total + LYTH_{guard}_BLOCK - 1u) / LYTH_{guard}_BLOCK;"
                ));
            }
            w("    if (g == 0u) g = 1u;");
            w(&format!(
                "    if (g > LYTH_{guard}_MAX_GRID) g = LYTH_{guard}_MAX_GRID;"
            ));
            w("    return g;");
        }
        crate::manifest::GridRule::Tiled { tile, extents } => {
            w("    /* One block per tile, not one thread per element. */");
            w("    unsigned long long blocks = 1ull;");
            for (e, t) in extents.iter().zip(tile) {
                w(&format!("    blocks *= ({e} + {}u) / {t}u;", t - 1));
            }
            w("    if (blocks == 0ull) blocks = 1ull;");
            w(&format!(
                "    if (blocks > LYTH_{guard}_MAX_GRID) return 0u;"
            ));
            w("    return (unsigned int)blocks;");
        }
    }
    w("}");
    w("");
    if let Some(p) = m.sized_by_grid() {
        w(&format!(
            "unsigned int lyth_{k}_{}_len({extent_args})",
            p.name
        ));
        w("{");
        w(&format!("    return lyth_{k}_grid({extent_pass});"));
        w("}");
        w("");
    }
    w(&format!(
        "CUresult lyth_{k}_load(CUmodule *module, CUfunction *fn)"
    ));
    w("{");
    w(&format!(
        "    CUresult r = cuModuleLoadData(module, lyth_{k}_ptx);"
    ));
    w("    if (r != CUDA_SUCCESS) return r;");
    w(&format!(
        "    return cuModuleGetFunction(fn, *module, LYTH_{guard}_KERNEL);"
    ));
    w("}");
    w("");
    w(&format!(
        "CUresult lyth_{k}_launch_with({})",
        ["CUfunction fn".to_string(), "unsigned int grid".to_string()]
            .into_iter()
            .chain(sig.iter().cloned())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    w("{");
    w(&format!(
        "    void *args[] = {{ {} }};",
        pass.iter()
            .map(|p| format!("(void *)&{p}"))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    w(&format!(
        "    return cuLaunchKernel(fn, grid, 1, 1, LYTH_{guard}_BLOCK, 1, 1,"
    ));
    w(&format!(
        "                          LYTH_{guard}_SHARED_BYTES, 0, args, 0);"
    ));
    w("}");
    w("");
    w(&format!(
        "CUresult lyth_{k}_launch({})",
        std::iter::once("CUfunction fn".to_string())
            .chain(sig.iter().cloned())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    w("{");
    w(&format!(
        "    unsigned int grid = lyth_{k}_grid({extent_pass});"
    ));
    w("    if (grid == 0u) return CUDA_ERROR_INVALID_VALUE;");
    w(&format!(
        "    return lyth_{k}_launch_with({});",
        std::iter::once("fn".to_string())
            .chain(std::iter::once("grid".to_string()))
            .chain(pass.iter().cloned())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    w("}");
    w("");
    w(&format!("#endif /* LYTH_{guard}_IMPLEMENTATION */"));
    w(&format!("#endif /* LYTH_{guard}_H */"));
    o
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_kernel_name_becomes_a_guard() {
        assert_eq!(upper("saxpy"), "SAXPY");
        assert_eq!(upper("max_of"), "MAX_OF");
    }

    #[test]
    fn ptx_is_escaped_line_by_line() {
        let lit = ptx_literal("// a \"quoted\" comment\n.version 8.7");
        assert!(lit.contains(r#"\"quoted\""#), "{lit}");
        assert!(lit.contains(r#"".version 8.7\n""#), "{lit}");
    }
}
