//! Rust bindings, generated from the manifest (ADR-0016).
//!
//! The output is a single file with no dependencies beyond `lyth-cuda`, which is the runtime
//! this repository already uses and tests. It embeds the PTX as a string constant rather than
//! reading a file at run time: a kernel that loads from disk is a kernel that can be out of
//! step with the binding that launches it.
//!
//! Two things the generated code does that hand-written glue usually does not.
//!
//! **A written buffer is `&mut`.** `Arg::Buf` only needs a shared reference, so this costs
//! nothing at the call and buys the borrow checker's opinion on aliasing: passing one buffer
//! as both the input and the output of a kernel stops compiling. LYTH's elementwise kernels
//! would often survive that aliasing, but "often" is not a property worth relying on, and the
//! generator cannot tell which kernels are the exceptions.
//!
//! **The contract is emitted as constants.** `DERIVED_INTENSITY`, `BYTES_PER_ELEMENT` and the
//! machine the kernel was checked against are in the generated file, so a caller can assert on
//! them in its own tests. That is the project's argument reduced to something a CI job reads.

use crate::manifest::Manifest;

/// `sum` becomes `Sum`, `saxpy_v2` becomes `SaxpyV2`.
fn type_name(kernel: &str) -> String {
    kernel
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// A raw-string delimiter that does not appear in the PTX, so the embedded module cannot be
/// terminated early by its own contents.
fn fence(ptx: &str) -> String {
    let mut hashes = 1;
    while ptx.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    "#".repeat(hashes)
}

pub fn generate(m: &Manifest, ptx: &str, source: &str) -> String {
    let ty = type_name(&m.kernel);
    let f = fence(ptx);

    // Read-only buffers take `&`, written ones `&mut`; scalars go by value.
    let arg = |p: &crate::manifest::ParamSpec| -> String {
        match p.ty.as_str() {
            "u32" => format!("{}: u32", p.name),
            "f32" => format!("{}: f32", p.name),
            _ if p.written => format!("{}: &mut Buffer<'_>", p.name),
            _ => format!("{}: &Buffer<'_>", p.name),
        }
    };
    let sig: Vec<String> = m.params.iter().map(arg).collect();
    let pass: Vec<String> = m.params.iter().map(|p| p.name.clone()).collect();
    let args: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.ty.as_str() {
            "u32" => format!("Arg::U32({})", p.name),
            "f32" => format!("Arg::F32({})", p.name),
            _ => format!("Arg::Buf({})", p.name),
        })
        .collect();

    // Every extent, not just the first: a rank-2 kernel is walked by the product of its
    // extents, and sizing the grid from one of them would launch a fraction of the work while
    // compiling cleanly.
    let extents: Vec<String> = m
        .params
        .iter()
        .filter(|p| p.is_extent)
        .map(|p| p.name.clone())
        .collect();
    let extent_args = extents
        .iter()
        .map(|e| format!("{e}: u32"))
        .collect::<Vec<_>>()
        .join(", ");
    let extent_pass = extents.join(", ");
    // The element count, as the generated code computes it.
    let elements = if extents.len() <= 1 {
        extents
            .first()
            .cloned()
            .unwrap_or_else(|| "n".to_string())
    } else {
        extents
            .iter()
            .map(|e| format!("{e} as u64"))
            .collect::<Vec<_>>()
            .join(" * ")
    };


    let declared = match m.contract.declared_intensity {
        Some(v) => format!("Some({v:?})"),
        None => "None".to_string(),
    };

    let mut out = String::new();
    let push = |out: &mut String, line: &str| {
        out.push_str(line);
        out.push('\n');
    };

    push(&mut out, &format!("// GENERATED BY LYTH from {source}. Do not edit."));
    push(&mut out, "//");
    push(&mut out, &format!("// {}", crate::manifest::contract_line(&m.contract)));
    for l in &m.known_limits {
        push(&mut out, &format!("// {l}"));
    }
    push(&mut out, "");
    push(&mut out, "use lyth_cuda::{Arg, Buffer, Context, CudaError, Function, Module};");
    push(&mut out, "");
    push(&mut out, &format!("pub const KERNEL: &str = \"{}\";", m.kernel));
    push(&mut out, &format!("pub const MACHINE: &str = \"{}\";", m.contract.machine));
    push(&mut out, &format!("pub const BLOCK: u32 = {};", m.launch.block));
    push(&mut out, &format!("pub const SHARED_BYTES: u32 = {};", m.launch.shared_bytes));
    push(&mut out, &format!("pub const MAX_GRID: u32 = {};", m.launch.max_grid));
    push(&mut out, "");
    push(&mut out, "/// What the source claimed, or `None` if it stayed silent.");
    push(&mut out, &format!("pub const DECLARED_INTENSITY: Option<f64> = {declared};"));
    match &m.contract.symbolic {
        // A cost that is a function of a launch extent becomes a function in the binding.
        //
        // The constants are **not** emitted for a contraction, and that is the point rather
        // than an omission. `unwrap_or(0.0)` published `BYTES_PER_ELEMENT: f64 = 0.0` for a
        // matmul -- the plausible-looking wrong number `Cost::bytes_per_element` was changed to
        // return `None` for. The type made it unreachable inside the compiler and this layer
        // handed it out anyway. A caller reaching for a constant that cannot describe this
        // kernel now fails to compile, which is the same protection one layer out.
        Some(sym) => {
            let k = &sym.extent;
            push(&mut out, "/// The limit the intensity approaches as the contracted extent grows.");
            push(&mut out, "///");
            push(&mut out, "/// There is no `DERIVED_INTENSITY` here: this kernel's exact intensity is a");
            push(&mut out, &format!("/// function of `{k}`, and a constant cannot be one. Use `derived_intensity`."));
            push(&mut out, &format!("pub const ASYMPTOTIC_INTENSITY: f64 = {:?};", sym.asymptotic_intensity));
            push(&mut out, "");
            push(&mut out, &format!("/// Bytes moved per output element at a known `{k}`: `{}`.", sym.bytes));
            push(&mut out, &format!("pub fn derived_bytes_per_element({k}: u32) -> f64 {{"));
            push(&mut out, &format!("    {:?} * {k} as f64 + {:?}", sym.bytes_per_extent, sym.bytes_fixed));
            push(&mut out, "}");
            push(&mut out, "");
            push(&mut out, &format!("/// FLOPs retired per output element at a known `{k}`: `{}`.", sym.flops));
            push(&mut out, &format!("pub fn derived_flops_per_element({k}: u32) -> f64 {{"));
            push(&mut out, &format!("    {:?} * {k} as f64 + {:?}", sym.flops_per_extent, sym.flops_fixed));
            push(&mut out, "}");
            push(&mut out, "");
            push(&mut out, "/// The exact intensity at a known extent, which is what a CI job can assert");
            push(&mut out, "/// on without a profiler.");
            push(&mut out, &format!("pub fn derived_intensity({k}: u32) -> f64 {{"));
            push(&mut out, &format!("    derived_flops_per_element({k}) / derived_bytes_per_element({k})"));
            push(&mut out, "}");
        }
        None => {
            push(&mut out, "/// What the compiler derived from the body. Assert on it if you care.");
            push(
                &mut out,
                &format!("pub const DERIVED_INTENSITY: f64 = {:?};", m.contract.derived_intensity),
            );
            push(
                &mut out,
                &format!(
                    "pub const FLOPS_PER_ELEMENT: f64 = {:?};",
                    m.contract.flops_per_element.expect("a constant contract has one")
                ),
            );
            push(
                &mut out,
                &format!(
                    "pub const BYTES_PER_ELEMENT: f64 = {:?};",
                    m.contract.bytes_per_element.expect("a constant contract has one")
                ),
            );
        }
    }
    push(&mut out, "");
    push(&mut out, &format!("pub const PTX: &str = r{f}\"{}\"{f};", ptx));
    push(&mut out, "");
    push(&mut out, "/// Elements the kernel walks: the product of its extents.");
    push(&mut out, "///");
    push(
        &mut out,
        "/// `None` when that product does not fit in a u32, which is the flattened index the",
    );
    push(
        &mut out,
        "/// kernel uses. At 4 bytes an element that is past 17 GB, so it cannot be reached on",
    );
    push(&mut out, "/// a device this kernel was compiled for.");
    push(&mut out, &format!("pub fn elements({extent_args}) -> Option<u32> {{"));
    if extents.len() <= 1 {
        push(&mut out, &format!("    Some({elements})"));
    } else {
        push(&mut out, &format!("    u32::try_from({elements}).ok()"));
    }
    push(&mut out, "}");
    push(&mut out, "");
    match &m.launch.grid {
        crate::manifest::GridRule::Elementwise {
            min_elements_per_thread,
            ..
        } => {
            if *min_elements_per_thread > 1 {
                push(&mut out, &format!(
                    "/// Blocks the default launch uses: at least {min_elements_per_thread} elements per thread, capped."
                ));
                push(&mut out, "///");
                push(&mut out, "/// Not one per thread. This kernel reduces, and at one element per");
                push(&mut out, "/// thread its shared-memory tree runs once per element: half the");
                push(&mut out, "/// achievable bandwidth, measured.");
            } else {
                push(&mut out, "/// Blocks the default launch uses: one element per thread, capped.");
            }
            // `BLOCK` alone when the floor is one, so an elementwise binding is not made to
            // read `BLOCK * 1`.
            let per_block = if *min_elements_per_thread > 1 {
                format!("(BLOCK * {min_elements_per_thread})")
            } else {
                "BLOCK".to_string()
            };
            push(&mut out, &format!("pub fn grid({extent_args}) -> Option<u32> {{"));
            push(
                &mut out,
                &format!(
                    "    Some(elements({extent_pass})?.div_ceil({per_block}).max(1).min(MAX_GRID))"
                ),
            );
            push(&mut out, "}");
        }
        crate::manifest::GridRule::Tiled { tile, extents } => {
            push(&mut out, "/// Blocks the default launch uses: one per tile.");
            push(&mut out, "///");
            push(&mut out, "/// Not the elementwise rule. A generator that reused that one would");
            push(&mut out, "/// launch a fraction of the work and compile cleanly doing it.");
            push(&mut out, &format!("pub fn grid({extent_args}) -> Option<u32> {{"));
            let terms: Vec<String> = extents
                .iter()
                .zip(tile)
                .map(|(e, t)| format!("{e}.div_ceil({t})"))
                .collect();
            push(&mut out, &format!("    let mut blocks: u32 = {};", terms[0]));
            for t in &terms[1..] {
                push(&mut out, &format!("    blocks = blocks.checked_mul({t})?;"));
            }
            push(&mut out, "    Some(blocks.max(1).min(MAX_GRID))");
            push(&mut out, "}");
        }
    }
    push(&mut out, "");

    if let Some(p) = m.params.iter().find(|p| p.sized_by_grid) {
        push(
            &mut out,
            &format!(
                "/// Elements `{}` must hold: one per block, **not** one per element.",
                p.name
            ),
        );
        push(
            &mut out,
            &format!("pub fn {}_len({extent_args}) -> Option<usize> {{", p.name),
        );
        push(&mut out, &format!("    Some(grid({extent_pass})? as usize)"));
        push(&mut out, "}");
        push(&mut out, "");
    }

    push(&mut out, "/// Load the embedded PTX. The module must outlive every launcher.");
    push(&mut out, "pub fn module(ctx: &Context) -> Result<Module<'_>, CudaError> {");
    push(&mut out, "    ctx.load_ptx(PTX)");
    push(&mut out, "}");
    push(&mut out, "");
    push(&mut out, &format!("pub struct {ty}<'m> {{"));
    push(&mut out, "    f: Function<'m>,");
    push(&mut out, "}");
    push(&mut out, "");
    push(&mut out, &format!("impl<'m> {ty}<'m> {{"));
    push(&mut out, "    pub fn new(module: &'m Module<'_>) -> Result<Self, CudaError> {");
    push(&mut out, "        Ok(Self { f: module.function(KERNEL)? })");
    push(&mut out, "    }");
    push(&mut out, "");
    push(&mut out, "    /// Launch at the compiler's default grid.");
    push(
        &mut out,
        &format!("    pub fn launch(&self, {}) -> Result<(), CudaError> {{", sig.join(", ")),
    );
    push(
        &mut out,
        &format!(
            "        let grid = grid({extent_pass})
            .ok_or_else(|| CudaError::Message(\"the extents overflow a u32 index\".into()))?;"
        ),
    );
    push(
        &mut out,
        &format!("        self.launch_with(grid, {})", pass.join(", ")),
    );
    push(&mut out, "    }");
    push(&mut out, "");
    push(&mut out, "    /// Launch at a grid of your choosing, for a sweep.");
    push(
        &mut out,
        &format!(
            "    pub fn launch_with(&self, grid: u32, {}) -> Result<(), CudaError> {{",
            sig.join(", ")
        ),
    );
    push(
        &mut out,
        &format!(
            "        self.f.launch_shared(grid, BLOCK, SHARED_BYTES, &[{}])",
            args.join(", ")
        ),
    );
    push(&mut out, "    }");
    push(&mut out, "}");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_kernel_name_becomes_a_type_name() {
        assert_eq!(type_name("sum"), "Sum");
        assert_eq!(type_name("saxpy"), "Saxpy");
        assert_eq!(type_name("max_of"), "MaxOf");
        assert_eq!(type_name("poly_v2_fast"), "PolyV2Fast");
    }

    #[test]
    fn the_fence_grows_until_the_ptx_cannot_close_it() {
        assert_eq!(fence("nothing awkward"), "#");
        // A PTX comment containing the closing sequence would end the literal early.
        assert_eq!(fence("// \"# oops"), "##");
        assert_eq!(fence("// \"# and \"## oops"), "###");
    }
}

#[cfg(test)]
mod tiled {
    use super::*;
    use crate::manifest::Manifest;
    use lyth_lang::{ir::lower, parse::parse};

    const SRC: &str = "machine sm_120\n\nkernel t(rows: u32, cols: u32, a: [f32; rows, cols], b: [f32; cols, rows])\n    space i, j : rows, cols\n    tile 32, 32\n    stream a : dram -> smem -> reg\n    stream b : dram -> reg, drain\n    at reg:\n        b[j, i] = a[i, j]\n";

    fn all_three() -> (String, String, String) {
        let unit = parse(SRC).unwrap();
        let ir = lower(&unit, &unit.kernels[0]).unwrap();
        let m = Manifest::of(&ir, None, 256, 1 << 20, vec![]);
        (
            generate(&m, "// ptx", "t.lyth"),
            crate::bind_c::generate(&m, "// ptx", "t.lyth"),
            crate::bind_py::generate(&m, "// ptx", "t.lyth"),
        )
    }

    #[test]
    fn every_binding_launches_one_block_per_tile() {
        // The elementwise rule would launch rows*cols/1024 blocks instead of
        // ceil(rows/32)*ceil(cols/32) -- a fraction of the work, compiling cleanly. This is
        // the failure the structured grid rule exists to prevent in all three at once.
        let (rs, c, py) = all_three();
        assert!(rs.contains("rows.div_ceil(32)") && rs.contains("cols.div_ceil(32)"), "{rs}");
        assert!(c.contains("(rows + 31u) / 32u") && c.contains("(cols + 31u) / 32u"), "{c}");
        assert!(py.contains("-(-rows // 32) * -(-cols // 32)"), "{py}");
        for s in [&rs, &c, &py] {
            assert!(!s.contains("BLOCK - 1"), "an elementwise rule leaked in");
        }
    }

    #[test]
    fn every_binding_carries_the_shared_bytes_so_the_caller_does_not() {
        // Rule 1 of ADR-0016: the signature of `launch` does not change when a kernel becomes
        // tiled. The 4224 is embedded, not a parameter.
        let (rs, c, py) = all_three();
        assert!(rs.contains("pub const SHARED_BYTES: u32 = 4224;"), "{rs}");
        assert!(c.contains("#define LYTH_T_SHARED_BYTES 4224u"), "{c}");
        assert!(py.contains("SHARED_BYTES = 4224"), "{py}");
        // And the block is the tile, not the compiler's 256.
        assert!(rs.contains("pub const BLOCK: u32 = 1024;"), "{rs}");
    }
}

#[cfg(test)]
mod reduction_grid {
    use super::*;
    use crate::manifest::Manifest;
    use lyth_lang::{ir::lower, parse::parse};

    const SUM: &str = "machine sm_120

kernel s(n: u32, x: [f32; n], partial: [f32; blocks])
    intensity 0.25
    stream x : dram -> reg
    reduce sum v : reg -> smem -> dram into partial
    at reg:
        v = x
";
    const SAXPY: &str = "machine sm_120

kernel k(n: u32, a: f32, x: [f32; n], y: [f32; n])
    intensity 0.1667
    stream x : dram -> reg
    stream y : dram -> reg, drain
    at reg:
        y = a * x + y
";

    fn all_three(src: &str) -> (String, String, String) {
        let unit = parse(src).unwrap();
        let ir = lower(&unit, &unit.kernels[0]).unwrap();
        let m = Manifest::of(&ir, None, 256, 1 << 20, vec![]);
        (
            generate(&m, "// ptx", "k.lyth"),
            crate::bind_c::generate(&m, "// ptx", "k.lyth"),
            crate::bind_py::generate(&m, "// ptx", "k.lyth"),
        )
    }

    #[test]
    fn every_binding_amortises_a_reduction_and_none_amortises_an_elementwise_kernel() {
        // The defect: `lyth run` was fixed to give a reduction eight elements per thread and
        // the generators went on emitting one, so a caller of the binding launched the same
        // kernel at half the achievable bandwidth. Three languages, one rule, asserted here
        // because the divergence was found by running a binding in another repository.
        let (rs, c, py) = all_three(SUM);
        assert!(rs.contains("div_ceil((BLOCK * 8))"), "{rs}");
        assert!(c.contains("LYTH_S_BLOCK * 8ull"), "{c}");
        assert!(py.contains("per_block = BLOCK * 8"), "{py}");

        let (rs, c, py) = all_three(SAXPY);
        assert!(rs.contains("div_ceil(BLOCK)") && !rs.contains("BLOCK * "), "{rs}");
        assert!(c.contains("(total + LYTH_K_BLOCK - 1u) / LYTH_K_BLOCK"), "{c}");
        assert!(py.contains("-(-total // BLOCK)") && !py.contains("per_block"), "{py}");
    }
}

#[cfg(test)]
mod symbolic_bindings {
    //! A cost that is a function of a launch extent becomes a function in the binding.
    //!
    //! The defect these exist for: `Cost::bytes_per_element` was changed to return `None` for a
    //! contraction, because the constant part of a matmul is 0 flops and 4 bytes and those are
    //! numbers that print without complaint. Three generators then wrote `unwrap_or(0.0)`, and
    //! the binding published `BYTES_PER_ELEMENT: f64 = 0.0` -- a matmul that moves nothing. The
    //! type made it unreachable inside the compiler and the layer whose job is to hand things
    //! out handed it out anyway.

    use super::*;
    use crate::manifest::Manifest;
    use lyth_lang::{ir::lower, parse::parse};

    const MATMUL: &str = "machine sm_120

kernel mm(m: u32, n: u32, k: u32,
              a: [f32; m, k], b: [f32; k, n], c: [f32; m, n])
    space i, j : m, n
    contract sum p : k
    tile 32, 32
    intensity asymptotic 8.0
    stream a : dram -> smem -> reg
    stream b : dram -> smem -> reg
    stream c : dram -> reg, drain
    at reg:
        c[i, j] = a[i, p] * b[p, j]
";
    const SAXPY: &str = "machine sm_120

kernel k(n: u32, a: f32, x: [f32; n], y: [f32; n])
    intensity 0.1667
    stream x : dram -> reg
    stream y : dram -> reg, drain
    at reg:
        y = a * x + y
";

    fn all_three(src: &str) -> (String, String, String) {
        let unit = parse(src).unwrap();
        let ir = lower(&unit, &unit.kernels[0]).unwrap();
        let m = Manifest::of(&ir, ir.cost.contracted.as_ref().map(|_| 8.0), 256, 1 << 20, vec![]);
        (
            generate(&m, "// ptx", "k.lyth"),
            crate::bind_c::generate(&m, "// ptx", "k.lyth"),
            crate::bind_py::generate(&m, "// ptx", "k.lyth"),
        )
    }

    #[test]
    fn a_contracted_binding_does_not_publish_a_constant_it_cannot_have() {
        // The absence is the assertion. A caller that reaches for `BYTES_PER_ELEMENT` gets a
        // compile error in Rust and C and an AttributeError in Python, rather than 0.0.
        // On the **declaration**, not on the substring: the binding's own doc comment says
        // "there is no `DERIVED_INTENSITY` here", and a test that cannot tell an explanation
        // from a definition is a test that forbids explaining anything.
        let (rs, c, py) = all_three(MATMUL);
        for name in ["BYTES_PER_ELEMENT", "FLOPS_PER_ELEMENT", "DERIVED_INTENSITY"] {
            assert!(!rs.contains(&format!("pub const {name}")), "{rs}");
            assert!(!c.contains(&format!("#define LYTH_MM_{name} ")), "{c}");
            assert!(
                !py.lines().any(|l| l.starts_with(&format!("{name} = "))),
                "{py}"
            );
        }
        // And nothing anywhere says this kernel moves nothing.
        for s in [&rs, &c, &py] {
            assert!(!s.contains("= 0.0;") && !s.contains("= 0.0
"), "a zero cost leaked:
{s}");
        }
    }

    #[test]
    fn it_publishes_the_expression_as_a_function_instead() {
        let (rs, c, py) = all_three(MATMUL);
        assert!(rs.contains("pub const ASYMPTOTIC_INTENSITY: f64 = 8.0;"), "{rs}");
        assert!(rs.contains("pub fn derived_bytes_per_element(k: u32) -> f64 {"), "{rs}");
        assert!(rs.contains("0.25 * k as f64 + 4.0"), "{rs}");
        assert!(rs.contains("pub fn derived_intensity(k: u32) -> f64 {"), "{rs}");

        assert!(c.contains("#define LYTH_MM_ASYMPTOTIC_INTENSITY 8.0"), "{c}");
        // `static inline`, not a function-like macro: the intensity needs its argument twice.
        assert!(c.contains("static inline double lyth_mm_derived_intensity(unsigned int k)"), "{c}");
        assert!(!c.contains("#define LYTH_MM_DERIVED_INTENSITY("), "a macro would double-evaluate:
{c}");

        assert!(py.contains("ASYMPTOTIC_INTENSITY = 8.0"), "{py}");
        assert!(py.contains("def derived_bytes_per_element(k):"), "{py}");
        assert!(py.contains("return 0.25 * k + 4.0"), "{py}");
    }

    #[test]
    fn the_functions_evaluate_to_what_the_compiler_derived() {
        // Not a test of the string: of the arithmetic in it. 4 * (2 * 4096 / 32 + 1) = 1028.
        let unit = parse(MATMUL).unwrap();
        let ir = lower(&unit, &unit.kernels[0]).unwrap();
        assert_eq!(ir.cost.bytes_at(4096), 1028.0);
        assert!((ir.cost.intensity_at(4096) - 7.9689).abs() < 1e-4);

        let (rs, _, _) = all_three(MATMUL);
        // The emitted coefficients are the ones the cost carries, so a reader checking the
        // generated line against the manifest is checking one number, not two.
        let c = ir.cost.contracted.as_ref().unwrap();
        assert!(rs.contains(&format!("{:?} * k as f64 + {:?}", c.bytes_per_extent, ir.cost.bytes_fixed())), "{rs}");
    }

    #[test]
    fn a_constant_kernel_keeps_the_constants_and_grows_no_functions() {
        // The change has to be invisible to every kernel written before a contraction, which
        // is what the checked-in saxpy fixtures also pin byte for byte.
        let (rs, c, py) = all_three(SAXPY);
        assert!(rs.contains("pub const BYTES_PER_ELEMENT: f64 = 12.0;"), "{rs}");
        assert!(rs.contains("pub const DERIVED_INTENSITY: f64 ="), "{rs}");
        assert!(!rs.contains("ASYMPTOTIC"), "{rs}");
        assert!(!rs.contains("derived_bytes_per_element"), "{rs}");
        assert!(c.contains("#define LYTH_K_BYTES_PER_ELEMENT 12.0"), "{c}");
        assert!(py.contains("BYTES_PER_ELEMENT = 12.0"), "{py}");
        assert!(!py.contains("def derived_bytes_per_element"), "{py}");
    }
}
