//! Rust bindings, generated from the manifest (ADR-0016).
//!
//! The output is a single file with no dependencies beyond `lyth-cuda`, which is the runtime
//! this repository already uses and tests. It embeds the PTX as a string constant rather than
//! reading a file at run time: a kernel that loads from disk is a kernel that can be out of
//! step with the binding that launches it.
//!
//! Two things the generated code does that hand-written glue usually does not.
//!
//! **A written buffer is `&mut`.** `Arg::Buf` only needs a shared reference, so this costs
//! nothing at the call and buys the borrow checker's opinion on aliasing: passing one buffer
//! as both the input and the output of a kernel stops compiling. LYTH's elementwise kernels
//! would often survive that aliasing, but "often" is not a property worth relying on, and the
//! generator cannot tell which kernels are the exceptions.
//!
//! **The contract is emitted as constants.** `DERIVED_INTENSITY`, `BYTES_PER_ELEMENT` and the
//! machine the kernel was checked against are in the generated file, so a caller can assert on
//! them in its own tests. That is the project's argument reduced to something a CI job reads.

use crate::manifest::Manifest;

/// `sum` becomes `Sum`, `saxpy_v2` becomes `SaxpyV2`.
fn type_name(kernel: &str) -> String {
    kernel
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// A raw-string delimiter that does not appear in the PTX, so the embedded module cannot be
/// terminated early by its own contents.
fn fence(ptx: &str) -> String {
    let mut hashes = 1;
    while ptx.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    "#".repeat(hashes)
}

pub fn generate(m: &Manifest, ptx: &str, source: &str) -> String {
    let ty = type_name(&m.kernel);
    let f = fence(ptx);

    // Read-only buffers take `&`, written ones `&mut`; scalars go by value.
    let arg = |p: &crate::manifest::ParamSpec| -> String {
        match p.ty.as_str() {
            "u32" => format!("{}: u32", p.name),
            "f32" => format!("{}: f32", p.name),
            _ if p.written => format!("{}: &mut Buffer<'_>", p.name),
            _ => format!("{}: &Buffer<'_>", p.name),
        }
    };
    let sig: Vec<String> = m.params.iter().map(arg).collect();
    let pass: Vec<String> = m.params.iter().map(|p| p.name.clone()).collect();
    let args: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.ty.as_str() {
            "u32" => format!("Arg::U32({})", p.name),
            "f32" => format!("Arg::F32({})", p.name),
            _ => format!("Arg::Buf({})", p.name),
        })
        .collect();

    let extent = m
        .extent()
        .map(|p| p.name.clone())
        .unwrap_or_else(|| "n".to_string());

    let declared = match m.contract.declared_intensity {
        Some(v) => format!("Some({v:?})"),
        None => "None".to_string(),
    };

    let mut out = String::new();
    let push = |out: &mut String, line: &str| {
        out.push_str(line);
        out.push('\n');
    };

    push(&mut out, &format!("// GENERATED BY LYTH from {source}. Do not edit."));
    push(&mut out, "//");
    push(
        &mut out,
        &format!(
            "// Contract: {:.4} flop/byte derived on {}, {} flop and {} byte per element.",
            m.contract.derived_intensity,
            m.contract.machine,
            m.contract.flops_per_element,
            m.contract.bytes_per_element
        ),
    );
    for l in &m.known_limits {
        push(&mut out, &format!("// {l}"));
    }
    push(&mut out, "");
    push(&mut out, "use lyth_cuda::{Arg, Buffer, Context, CudaError, Function, Module};");
    push(&mut out, "");
    push(&mut out, &format!("pub const KERNEL: &str = \"{}\";", m.kernel));
    push(&mut out, &format!("pub const MACHINE: &str = \"{}\";", m.contract.machine));
    push(&mut out, &format!("pub const BLOCK: u32 = {};", m.launch.block));
    push(&mut out, &format!("pub const SHARED_BYTES: u32 = {};", m.launch.shared_bytes));
    push(&mut out, &format!("pub const MAX_GRID: u32 = {};", m.launch.max_grid));
    push(&mut out, "");
    push(&mut out, "/// What the source claimed, or `None` if it stayed silent.");
    push(&mut out, &format!("pub const DECLARED_INTENSITY: Option<f64> = {declared};"));
    push(&mut out, "/// What the compiler derived from the body. Assert on it if you care.");
    push(
        &mut out,
        &format!("pub const DERIVED_INTENSITY: f64 = {:?};", m.contract.derived_intensity),
    );
    push(
        &mut out,
        &format!("pub const FLOPS_PER_ELEMENT: f64 = {:?};", m.contract.flops_per_element),
    );
    push(
        &mut out,
        &format!("pub const BYTES_PER_ELEMENT: f64 = {:?};", m.contract.bytes_per_element),
    );
    push(&mut out, "");
    push(&mut out, &format!("pub const PTX: &str = r{f}\"{}\"{f};", ptx));
    push(&mut out, "");
    push(&mut out, "/// Blocks the default launch uses: one element per thread, capped.");
    push(&mut out, &format!("pub fn grid({extent}: u32) -> u32 {{"));
    push(&mut out, &format!("    {extent}.div_ceil(BLOCK).max(1).min(MAX_GRID)"));
    push(&mut out, "}");
    push(&mut out, "");

    if let Some(p) = m.params.iter().find(|p| p.sized_by_grid) {
        push(
            &mut out,
            &format!(
                "/// Elements `{}` must hold: one per block, **not** one per element.",
                p.name
            ),
        );
        push(&mut out, &format!("pub fn {}_len({extent}: u32) -> usize {{", p.name));
        push(&mut out, &format!("    grid({extent}) as usize"));
        push(&mut out, "}");
        push(&mut out, "");
    }

    push(&mut out, "/// Load the embedded PTX. The module must outlive every launcher.");
    push(&mut out, "pub fn module(ctx: &Context) -> Result<Module<'_>, CudaError> {");
    push(&mut out, "    ctx.load_ptx(PTX)");
    push(&mut out, "}");
    push(&mut out, "");
    push(&mut out, &format!("pub struct {ty}<'m> {{"));
    push(&mut out, "    f: Function<'m>,");
    push(&mut out, "}");
    push(&mut out, "");
    push(&mut out, &format!("impl<'m> {ty}<'m> {{"));
    push(&mut out, "    pub fn new(module: &'m Module<'_>) -> Result<Self, CudaError> {");
    push(&mut out, "        Ok(Self { f: module.function(KERNEL)? })");
    push(&mut out, "    }");
    push(&mut out, "");
    push(&mut out, "    /// Launch at the compiler's default grid.");
    push(
        &mut out,
        &format!("    pub fn launch(&self, {}) -> Result<(), CudaError> {{", sig.join(", ")),
    );
    push(
        &mut out,
        &format!("        self.launch_with(grid({extent}), {})", pass.join(", ")),
    );
    push(&mut out, "    }");
    push(&mut out, "");
    push(&mut out, "    /// Launch at a grid of your choosing, for a sweep.");
    push(
        &mut out,
        &format!(
            "    pub fn launch_with(&self, grid: u32, {}) -> Result<(), CudaError> {{",
            sig.join(", ")
        ),
    );
    push(
        &mut out,
        &format!(
            "        self.f.launch_shared(grid, BLOCK, SHARED_BYTES, &[{}])",
            args.join(", ")
        ),
    );
    push(&mut out, "    }");
    push(&mut out, "}");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_kernel_name_becomes_a_type_name() {
        assert_eq!(type_name("sum"), "Sum");
        assert_eq!(type_name("saxpy"), "Saxpy");
        assert_eq!(type_name("max_of"), "MaxOf");
        assert_eq!(type_name("poly_v2_fast"), "PolyV2Fast");
    }

    #[test]
    fn the_fence_grows_until_the_ptx_cannot_close_it() {
        assert_eq!(fence("nothing awkward"), "#");
        // A PTX comment containing the closing sequence would end the literal early.
        assert_eq!(fence("// \"# oops"), "##");
        assert_eq!(fence("// \"# and \"## oops"), "###");
    }
}
