//! Source to PTX, end to end, with no GPU.
//!
//! These run the real `examples/*.lyth` files through the real pipeline, so an example that
//! stops compiling fails the build rather than being discovered by a reader. The launch and
//! the bit-exact check need a device and live in `lyth run`; everything up to the module is
//! checked here.

use std::path::PathBuf;

use lyth_lang::{ir, parse};
use lyth_ptx::emit;

fn example(name: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../examples")
        .join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn compile(name: &str) -> Result<lyth_ptx::Module, String> {
    let src = example(name);
    let unit = parse(&src).map_err(|e| e.to_string())?;
    let kernel = &unit.kernels[0];
    let ir = ir::lower(&unit, kernel).map_err(|e| e.to_string())?;
    if let Some(declared) = kernel.declared_intensity {
        lyth_lang::check_intensity(&ir, Some(declared), None, 0.05).map_err(|e| e.to_string())?;
    }
    emit(&ir, "sm_120").map_err(|e| e.to_string())
}

#[test]
fn saxpy_compiles_and_moves_what_it_says() {
    let m = compile("saxpy.lyth").expect("saxpy should compile");
    assert!(m.ptx.contains(".target sm_120"));
    assert_eq!(m.entry, "saxpy");
    // 8 bytes read as two loads, 4 written as one store — the derived model, in instructions.
    assert_eq!(m.ptx.matches("ld.global.f32").count(), 2);
    assert_eq!(m.ptx.matches("st.global.f32").count(), 1);
    assert_eq!(m.ptx.matches("fma.rn.f32").count(), 1);
}

#[test]
fn the_lying_example_does_not_compile() {
    let e = compile("saxpy-lie.lyth").expect_err("an intensity lie must not compile");
    assert!(e.contains("body computes 0.1667"), "{e}");
    assert!(e.contains("did you mean to declare"), "{e}");
}

#[test]
fn the_example_that_forgets_a_stream_does_not_compile() {
    let e = compile("forgot-stream.lyth").expect_err("an unstreamed read must not compile");
    assert!(e.contains("no stream moves it"), "{e}");
}

#[test]
fn the_generated_ptx_records_the_cost_it_was_compiled_under() {
    // A .ptx file that outlives its source should still say what the compiler believed, so a
    // reader can check the claim without the toolchain that produced it.
    let m = compile("saxpy.lyth").unwrap();
    assert!(m.ptx.contains("Generated by LYTH"), "{}", m.ptx);
    assert!(m.ptx.contains("0.166667 flop/byte"), "{}", m.ptx);
    assert!(m.ptx.contains("8 read + 4 written"), "{}", m.ptx);
}

/// Every example in `examples/` that is meant to compile, with the cost the compiler should
/// derive for it. An example that stops compiling, or whose cost moves, fails here rather than
/// being found by a reader.
#[test]
fn every_working_example_compiles_with_the_cost_it_documents() {
    // name, flops/element, bytes/element, loads, stores
    let cases: &[(&str, f64, f64, usize, usize)] = &[
        ("saxpy.lyth", 2.0, 12.0, 2, 1),
        ("axpby.lyth", 3.0, 12.0, 2, 1),
        ("horner.lyth", 6.0, 8.0, 1, 1),
        ("lerp.lyth", 3.0, 12.0, 2, 1),
        ("split.lyth", 3.0, 12.0, 1, 2),
        // Reductions: the store is the block partial, written by thread 0.
        ("dot.lyth", 2.0, 8.0, 2, 1),
        ("sum.lyth", 1.0, 4.0, 1, 1),
    ];
    for (name, flops, bytes, loads, stores) in cases {
        let src = example(name);
        let unit = parse(&src).unwrap_or_else(|e| panic!("{name}: {e}"));
        let ir = ir::lower(&unit, &unit.kernels[0]).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(ir.cost.flops_per_element, *flops, "{name} flops");
        assert_eq!(ir.cost.bytes_per_element(), *bytes, "{name} bytes");
        let m = emit(&ir, "sm_120").unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(
            m.ptx.matches("ld.global.f32").count(),
            *loads,
            "{name} loads"
        );
        assert_eq!(
            m.ptx.matches("st.global.f32").count(),
            *stores,
            "{name} stores"
        );
    }
}

#[test]
fn horner_becomes_a_chain_of_fused_multiply_adds() {
    // The point of the example: same traffic as a copy, six times the arithmetic. One load,
    // three fma, one store is what hand-written CUDA compiles to for the same polynomial.
    let m = compile("horner.lyth").expect("horner should compile");
    assert_eq!(m.ptx.matches("fma.rn.f32").count(), 3, "{}", m.ptx);
    assert_eq!(m.ptx.matches("mul.rn.f32").count(), 0, "{}", m.ptx);
    assert_eq!(m.ptx.matches("ld.global.f32").count(), 1, "{}", m.ptx);
}

#[test]
fn a_reduction_emits_a_shared_tree_and_one_store_per_block() {
    let m = compile("dot.lyth").expect("dot should compile");
    // Dynamic shared memory, so the block size is not baked into the module.
    assert!(m.ptx.contains(".extern .shared"), "{}", m.ptx);
    // Both barriers: after the initial store, and after each combine.
    assert_eq!(m.ptx.matches("bar.sync 0;").count(), 2, "{}", m.ptx);
    assert!(m.ptx.contains("ld.shared.f32"), "{}", m.ptx);
    assert!(m.ptx.contains("st.shared.f32"), "{}", m.ptx);
    // One global store, guarded on tid == 0.
    assert_eq!(m.ptx.matches("st.global.f32").count(), 1, "{}", m.ptx);
    assert!(m.ptx.contains("setp.ne.u32"), "{}", m.ptx);
    // The per-thread fold happens inside the loop, before the tree.
    assert!(m.ptx.contains("add.rn.f32"), "{}", m.ptx);
}

#[test]
fn a_local_nothing_consumes_does_not_compile() {
    let e = compile("dead-local.lyth").expect_err("dead work must not compile");
    assert!(e.contains("computed and then discarded"), "{e}");
}

#[test]
fn streaming_a_reduction_target_does_not_compile() {
    // Streaming it would claim per-element traffic for a buffer written once per block,
    // which inflates the byte count and understates the intensity.
    let e = compile("reduce-streamed.lyth").expect_err("must not compile");
    assert!(e.contains("one value per BLOCK"), "{e}");
}

#[test]
fn the_cost_model_reports_shared_traffic_beside_dram_not_mixed_into_it() {
    let src = example("dot.lyth");
    let unit = parse(&src).unwrap();
    let ir = ir::lower(&unit, &unit.kernels[0]).unwrap();
    let dram = ir.cost.at(lyth_lang::Level::Dram).expect("dram traffic");
    let smem = ir.cost.at(lyth_lang::Level::Smem).expect("smem traffic");
    assert_eq!(dram.total(), 8.0, "x and y, per element");
    assert_eq!(smem.total(), 16.0, "the tree");
    // The roofline is about DRAM. Folding the shared traffic in would move it.
    assert_eq!(ir.cost.bytes_per_element(), 8.0);
    assert_eq!(ir.cost.intensity, 0.25);
    // The partial is one write per block, reported separately rather than divided by a
    // block size the compiler would have to invent.
    assert_eq!(ir.cost.dram_bytes_per_block, 4.0);
}

#[test]
fn every_kernel_loops_over_a_grid_stride() {
    // The grid stops being a function of n, which is what makes the launch shape something
    // that can be varied and therefore measured (ADR-0012).
    for name in ["saxpy.lyth", "horner.lyth", "dot.lyth"] {
        let m = compile(name).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(m.ptx.contains("mov.u32"), "{name}");
        assert!(m.ptx.contains("%nctaid.x"), "{name}: no stride");
        assert!(m.ptx.contains("mul.lo.s32"), "{name}: stride not computed");
        let head = m.ptx.matches("$L_loop_").count();
        assert!(head >= 3, "{name}: loop label, branch back and exit");
    }
}

#[test]
fn grid_stride_deletes_the_idle_thread_branch_from_a_reduction() {
    // Under one-element-per-thread a thread with no element had to be routed to a label that
    // loaded the identity. With a grid-stride accumulator it simply never enters the loop, so
    // that branch is gone and the accumulator starts at the identity instead.
    let m = compile("dot.lyth").unwrap();
    assert!(
        !m.ptx.contains("$L_idle_"),
        "the idle branch should be gone:
{}",
        m.ptx
    );
    assert!(m.ptx.contains("mov.f32 %f1, 0f00000000"), "{}", m.ptx);
    // Still exactly two barriers, and still one store guarded on thread 0.
    assert_eq!(m.ptx.matches("bar.sync 0;").count(), 2, "{}", m.ptx);
    assert_eq!(m.ptx.matches("st.global.f32").count(), 1, "{}", m.ptx);
}
