//! LYTH to Unibit assembly. ADR-0025 step 2.
//!
//! The other back end emits a kernel. **This one emits a program**: `.data`, `.text`,
//! `_start`, and a `halt`. That difference is the whole reason the target exists — a `.cu`
//! file is not a program and neither is a `.lyth` one, because a GPU has no entry point and
//! something on a CPU must launch it. Unibit does have one, so a `.lyth` file compiled for it
//! is something you run.
//!
//! ## The mapping
//!
//! | LYTH | Unibit |
//! |---|---|
//! | `space i : n` | a bounded loop, eight elements an iteration |
//! | `stream x : dram -> reg` | `LQ` — one 256-bit load is eight f32 |
//! | a scalar `f32` parameter | `VSPLAT.w`, broadcast once before the loop |
//! | `y = a * x + y` | `VFMA`, or `VFMUL` and `VFADD` |
//! | `stream y : ..., drain` | `SQ` |
//!
//! Eight lanes an instruction is not a tiling choice the compiler made: it is the register.
//! `Reg256` is 256 bits and an f32 is 32, so the loop steps by eight because that is what one
//! load holds.
//!
//! ## What it refuses, and why each is a refusal rather than a lowering
//!
//! Step 2 is elementwise, rank 1. Everything else is refused **by name**, because a back end
//! that quietly lowers what it does not understand produces output nobody can reason about.
//! `tile` and `coarsen` are refused *permanently* on this machine rather than pending: Unibit
//! has no shared memory, `fixtures/machine/unibit.json` names no `smem` level, and ADR-0022
//! made the ceiling a minimum over the levels a machine names. A kernel that stages where
//! there is nothing to stage into is asking for a level that does not exist.

use std::fmt::Write;

use lyth_lang::ast::{BinOp, Ty};
use lyth_lang::ir::{KernelIr, Op, RegId};

/// Elements one 256-bit register holds at `f32`. Not a tunable.
pub const LANES: u32 = 8;

/// The value `lyth run` gives a scalar that was not `--set`, so the emitted program and the
/// host oracle agree about it. Duplicated from `main.rs` and asserted equal in the tests,
/// which is the honest form of a constant that has to live in two crates.
pub const DEFAULT_SCALAR: f32 = 2.0;

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct EmitError(pub String);

fn refuse(msg: impl Into<String>) -> EmitError {
    EmitError(msg.into())
}

/// Emit a complete, runnable Unibit program for this kernel at `n` elements.
///
/// The inputs are baked into `.data` by `lyth_lang::inputs` — the **same** generator the host
/// oracle uses. A program computing on different numbers from the oracle would make every
/// comparison between them a comparison of two functions.
pub fn emit_program(ir: &KernelIr, n: u32) -> Result<String, EmitError> {
    check_scope(ir, n)?;

    let mut out = String::new();
    let _ = writeln!(out, "; Generated by LYTH from kernel `{}`.", ir.name);
    let _ = writeln!(
        out,
        "; ADR-0025 step 2: elementwise, rank 1, n = {n}, {LANES} elements per register."
    );
    let _ = writeln!(
        out,
        "; Inputs are lyth_lang::inputs, the generator the host oracle uses."
    );
    let _ = writeln!(out);
    emit_data(ir, n, &mut out);
    emit_text(ir, n, &mut out)?;
    Ok(out)
}

/// Everything step 2 does not do, said by name.
fn check_scope(ir: &KernelIr, n: u32) -> Result<(), EmitError> {
    if ir.tile.is_some() {
        return Err(refuse(format!(
            "kernel `{}` declares a tile, and `unibit` has no shared memory to stage into.\n  \
             A tile buys reuse by putting a block's worth of elements somewhere every thread \
             can reach; this machine names no `smem` level, so there is nowhere,\n  and the \
             tile would be a declaration that changes nothing. Drop it for this target.",
            ir.name
        )));
    }
    if ir.contract.is_some() {
        return Err(refuse(format!(
            "kernel `{}` contracts, and this back end does not emit a contraction (ADR-0025 \
             step 3).",
            ir.name
        )));
    }
    if ir.reduction.is_some() {
        return Err(refuse(format!(
            "kernel `{}` reduces. `VREDUCE` exists on this machine and wiring it is ADR-0025 \
             step 3; until then this is refused rather than lowered to something else.",
            ir.name
        )));
    }
    if let Some(space) = &ir.space {
        if space.vars.len() != 1 {
            return Err(refuse(format!(
                "kernel `{}` walks a rank-{} space; this back end emits rank 1 (ADR-0025 step \
                 2). The row-major address arithmetic a rank-2 space needs is step 3's.",
                ir.name,
                space.vars.len()
            )));
        }
    }
    if !n.is_multiple_of(LANES) {
        return Err(refuse(format!(
            "n = {n} is not a multiple of {LANES}.\n  One 256-bit register holds {LANES} f32 \
             and this back end emits no tail loop, so a ragged n would silently compute fewer \
             elements than asked for.\n  Refused rather than rounded."
        )));
    }
    if let Some(p) = ir
        .params
        .iter()
        .find(|p| p.ty == Ty::BufF16 || p.ty == Ty::BufBF16)
    {
        return Err(refuse(format!(
            "`{}` is a narrow buffer and `unibit`'s float unit is packed single precision only \
             (ADR-0025 step 0): there is no `cvt.f32.f16`.\n  Refused rather than emitted as \
             f32, which would move twice the bytes the cost model derived.",
            p.name
        )));
    }
    Ok(())
}

fn emit_data(ir: &KernelIr, n: u32, out: &mut String) {
    let _ = writeln!(out, "        .data");
    for p in &ir.params {
        if !p.ty.is_buffer() {
            continue;
        }
        let words: Vec<String> = lyth_lang::inputs::buffer(&p.name, p.ty, n)
            .iter()
            .map(|v| format!("0x{:08X}", v.to_bits()))
            .collect();
        // One `.word` directive per buffer, never several. Two directives under one label do
        // not land contiguously in this assembler, and `LQ` then reads the end of one buffer
        // followed by the start of whatever sits next -- which assembles, runs, and prints
        // numbers. Found writing `Unibit/programs/saxpy_f32.uasm`.
        let _ = writeln!(out, "{:<8}.word {}", format!("{}:", p.name), words.join(", "));
    }
    let _ = writeln!(out);
}

fn emit_text(ir: &KernelIr, n: u32, out: &mut String) -> Result<(), EmitError> {
    let _ = writeln!(out, "        .text");
    let _ = writeln!(out, "        .global _start");
    let _ = writeln!(out, "_start:");

    let buffers: Vec<&str> = ir
        .params
        .iter()
        .filter(|p| p.ty.is_buffer())
        .map(|p| p.name.as_str())
        .collect();
    if buffers.len() > 8 {
        return Err(refuse(format!(
            "kernel `{}` has {} buffers; this back end keeps one base pointer per saved \
             register, s0 through s7.",
            ir.name,
            buffers.len()
        )));
    }
    for (i, b) in buffers.iter().enumerate() {
        let _ = writeln!(out, "        la      s{i}, {b}");
    }

    let mut next_t = 0usize;
    let mut alloc = |out: &mut String| -> Result<String, EmitError> {
        // t0..t6 are the seven temporaries this ISA names. Running out is a real limit and is
        // reported as one rather than wrapping around and corrupting a live value.
        if next_t >= 7 {
            return Err(refuse(
                "the body needs more than seven live values and this back end does not spill. \
                 A longer expression is a real limit here, not a bug.",
            ));
        }
        let r = format!("t{next_t}");
        next_t += 1;
        let _ = out;
        Ok(r)
    };

    // Scalars, broadcast once before the loop. `VSPLAT.w` copies the low 32 bits into all
    // eight lanes, and an f32 is bits, so the integer instruction serves a float unchanged.
    let mut scalar_reg: Vec<(String, String)> = Vec::new();
    for p in &ir.params {
        if p.ty != Ty::F32 {
            continue;
        }
        let r = alloc(out)?;
        let _ = writeln!(
            out,
            "        li      {r}, 0x{:08X}",
            DEFAULT_SCALAR.to_bits()
        );
        let _ = writeln!(out, "        vsplat.w {r}, {r}");
        scalar_reg.push((p.name.clone(), r));
    }

    let iters = n / LANES;
    let _ = writeln!(out, "        li      s8, {iters}");
    let _ = writeln!(out, "loop:");

    let mut regs: Vec<(RegId, String)> = Vec::new();
    fn get(regs: &[(RegId, String)], id: RegId) -> String {
        regs.iter()
            .find(|(i, _)| *i == id)
            .map(|(_, r)| r.clone())
            .expect("SSA: every use follows its definition")
    }

    for op in &ir.ops {
        match op {
            Op::Load { dst, buffer } => {
                let i = buffers
                    .iter()
                    .position(|b| b == buffer)
                    .expect("a streamed buffer is a parameter");
                let r = alloc(out)?;
                let _ = writeln!(out, "        lq      {r}, 0(s{i})");
                regs.push((*dst, r));
            }
            Op::Param { dst, name } => {
                let r = scalar_reg
                    .iter()
                    .find(|(n, _)| n == name)
                    .map(|(_, r)| r.clone())
                    .ok_or_else(|| refuse(format!("`{name}` is not a broadcast scalar")))?;
                regs.push((*dst, r));
            }
            Op::Const { dst, value } => {
                let r = alloc(out)?;
                let _ = writeln!(
                    out,
                    "        li      {r}, 0x{:08X}",
                    (*value as f32).to_bits()
                );
                let _ = writeln!(out, "        vsplat.w {r}, {r}");
                regs.push((*dst, r));
            }
            Op::Bin { dst, op, lhs, rhs } => {
                let m = match op {
                    BinOp::Add => "vfadd",
                    BinOp::Sub => "vfsub",
                    BinOp::Mul => "vfmul",
                    BinOp::Div => {
                        return Err(refuse(
                            "this machine has no packed float divide. ADR-0025 step 0 added \
                             add, sub, mul, fma, max and min, and a divide is not among them.",
                        ))
                    }
                };
                let (l, r2) = (get(&regs, *lhs), get(&regs, *rhs));
                let r = alloc(out)?;
                let _ = writeln!(out, "        {m}   {r}, {l}, {r2}");
                regs.push((*dst, r));
            }
            Op::Fma { dst, a, b, c } => {
                // `VFMA` accumulates into `rd`, so the addend has to be there before the
                // instruction runs. Copying rather than writing into `c`'s register keeps SSA
                // intact: `c` may be read again later in the body.
                let (ra, rb, rc) = (get(&regs, *a), get(&regs, *b), get(&regs, *c));
                let r = alloc(out)?;
                let _ = writeln!(out, "        mv      {r}, {rc}");
                let _ = writeln!(out, "        vfma    {r}, {ra}, {rb}");
                regs.push((*dst, r));
            }
            Op::Neg { dst, src } => {
                // No packed float negate either. `0 - x` is exact, and it is said out loud
                // because a reader counting instructions should know where the extra two came
                // from.
                let s = get(&regs, *src);
                let z = alloc(out)?;
                let r = alloc(out)?;
                let _ = writeln!(out, "        li      {z}, 0");
                let _ = writeln!(out, "        vsplat.w {z}, {z}");
                let _ = writeln!(out, "        vfsub   {r}, {z}, {s}");
                regs.push((*dst, r));
            }
        }
    }

    for (buffer, src) in &ir.drains {
        let i = buffers
            .iter()
            .position(|b| b == buffer)
            .expect("a drained buffer is a parameter");
        let _ = writeln!(out, "        sq      {}, 0(s{i})", get(&regs, *src));
    }

    for (i, _) in buffers.iter().enumerate() {
        let _ = writeln!(out, "        addi    s{i}, s{i}, 32");
    }
    let _ = writeln!(out, "        addi    s8, s8, -1");
    let _ = writeln!(out, "        bne     s8, zero, loop");

    // Print every drained buffer, so the oracle has something to compare against.
    //
    // `PRINT_REG256` takes a register **index**, not a name, and that bites: `t0` is `x5`.
    // Writing `li a0, 0` because the value is in `t0` prints `zero` and looks like a kernel
    // that computed nothing -- which cost an hour in `Unibit/programs/saxpy_f32.uasm`.
    for (buffer, _) in &ir.drains {
        let i = buffers
            .iter()
            .position(|b| b == buffer)
            .expect("a drained buffer is a parameter");
        let _ = writeln!(out, "        la      s{i}, {buffer}");
        let _ = writeln!(out, "        li      s9, {iters}");
        let _ = writeln!(out, "print_{buffer}:");
        let _ = writeln!(out, "        lq      t0, 0(s{i})");
        let _ = writeln!(out, "        li      a0, 5          ; t0 is x5");
        let _ = writeln!(out, "        li      a7, 20         ; print_reg256");
        let _ = writeln!(out, "        ecall");
        let _ = writeln!(out, "        addi    s{i}, s{i}, 32");
        let _ = writeln!(out, "        addi    s9, s9, -1");
        let _ = writeln!(out, "        bne     s9, zero, print_{buffer}");
    }

    let _ = writeln!(out, "        halt");
    Ok(())
}
