//! LYTH to Unibit assembly. ADR-0025 steps 2 to 4.
//!
//! The other back end emits a kernel. **This one emits a program**: `.data`, `.text`,
//! `_start`, and a `halt`. That difference is the whole reason the target exists — a `.cu`
//! file is not a program and neither is a `.lyth` one, because a GPU has no entry point and
//! something on a CPU must launch it. Unibit does have one, so a `.lyth` file compiled for it
//! is something you run.
//!
//! ## The mapping
//!
//! | LYTH | Unibit |
//! |---|---|
//! | `space i : n` | a bounded loop, eight elements an iteration |
//! | `space i, j : rows, cols` | the same loop over `rows * cols`, when nothing is permuted |
//! | `stream x : dram -> reg` | `LQ` — one 256-bit load is eight f32 |
//! | a scalar `f32` parameter | `VSPLAT.w`, broadcast once before the loop |
//! | `y = a * x + y` | `VFMA`, or `VFMUL` and `VFADD` |
//! | `stream y : ..., drain` | `SQ` |
//! | `reduce sum : reg -> dram` | a partial per lane, then `VFREDUCE` and one `SW` |
//!
//! Eight lanes an instruction is not a tiling choice the compiler made: it is the register.
//! `Reg256` is 256 bits and an f32 is 32, so the loop steps by eight because that is what one
//! load holds.
//!
//! ## What it refuses, and why each is a refusal rather than a lowering
//!
//! Everything outside that table is refused **by name**, because a back end that quietly lowers
//! what it does not understand produces output nobody can reason about. `tile` and `coarsen`
//! are refused *permanently* on this machine rather than pending: Unibit has no shared memory,
//! `fixtures/machine/unibit.json` names no `smem` level, and ADR-0022 made the ceiling a
//! minimum over the levels a machine names. A kernel that stages where there is nothing to
//! stage into is asking for a level that does not exist.
//!
//! A **permuted** rank-2 access is refused for a different reason, and a harder one: `SQ` is
//! the only vector store and it writes 32 contiguous bytes. There is no strided store, no
//! scatter and no lane extract, so `b[j, i] = a[i, j]` cannot be emitted here slowly either.

use std::fmt::Write;

use std::collections::BTreeMap;

use lyth_lang::ast::{BinOp, Level, ReduceOp, Ty};
use lyth_lang::program::{PrintRange, Program};
use lyth_lang::ir::{KernelIr, Op, RegId};

/// Elements one 256-bit register holds at `f32`. Not a tunable.
pub const LANES: u32 = 8;

/// The value `lyth run` gives a scalar that was not `--set`, so the emitted program and the
/// host oracle agree about it. Duplicated from `main.rs` and asserted equal in the tests,
/// which is the honest form of a constant that has to live in two crates.
pub const DEFAULT_SCALAR: f32 = 2.0;

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct EmitError(pub String);

fn refuse(msg: impl Into<String>) -> EmitError {
    EmitError(msg.into())
}

/// Emit a complete, runnable Unibit program for this kernel at `n` elements, printing every
/// result it produces.
///
/// The `main`-less shape: what a kernel would print if the file did not say. `lyth build` on a
/// source with a `main` goes through [`emit`] instead, and both end in the same code, because
/// a second way to describe one launch is how ADR-0019's two descriptions of a grid drifted.
pub fn emit_program(ir: &KernelIr, n: u32) -> Result<String, EmitError> {
    let mut scalars = BTreeMap::new();
    for p in &ir.params {
        if p.ty == Ty::F32 {
            scalars.insert(p.name.clone(), DEFAULT_SCALAR);
        }
    }
    // Everything the kernel writes: the drained buffers, or the reduction's one value.
    let prints = match &ir.reduction {
        Some(r) => vec![PrintRange {
            buffer: r.into.clone(),
            lo: 0,
            hi: 1,
        }],
        None => ir
            .drains
            .iter()
            .map(|(b, _)| PrintRange {
                buffer: b.clone(),
                lo: 0,
                hi: n,
            })
            .collect(),
    };
    emit(
        ir,
        &Program {
            n,
            extents: BTreeMap::new(),
            scalars,
            prints,
        },
    )
}

/// Emit the program a resolved `main` describes.
///
/// The inputs are baked into `.data` by `lyth_lang::inputs` — the **same** generator the host
/// oracle uses. A program computing on different numbers from the oracle would make every
/// comparison between them a comparison of two functions.
pub fn emit(ir: &KernelIr, p: &Program) -> Result<String, EmitError> {
    let n = p.n;
    check_scope(ir, n)?;

    let mut out = String::new();
    let _ = writeln!(out, "; Generated by LYTH from kernel `{}`.", ir.name);
    let _ = writeln!(
        out,
        "; ADR-0025 step 4: n = {n} elements, {LANES} per register, {} iterations.",
        n / LANES
    );
    let _ = writeln!(
        out,
        "; Inputs are lyth_lang::inputs, the generator the host oracle uses."
    );
    // The contract, in the file the machine runs. A program that carries the intensity it was
    // checked against can be read against its own counters later without a second artifact.
    if let Some(b) = ir.cost.bytes_per_element() {
        let _ = writeln!(
            out,
            "; Contract: {:.4} flop/byte ({} flop / {b} byte per element).",
            ir.cost.intensity_at(1),
            ir.cost.flops_expr().unwrap_or_default()
        );
    }
    let _ = writeln!(out);
    emit_data(ir, p, &mut out);
    emit_text(ir, p, &mut out)?;
    Ok(out)
}

/// Everything this back end does not do, said by name.
fn check_scope(ir: &KernelIr, n: u32) -> Result<(), EmitError> {
    if ir.tile.is_some() {
        return Err(refuse(format!(
            "kernel `{}` declares a tile, and `unibit` has no shared memory to stage into.\n  \
             A tile buys reuse by putting a block's worth of elements somewhere every thread \
             can reach; this machine names no `smem` level, so there is nowhere,\n  and the \
             tile would be a declaration that changes nothing. Drop it for this target.",
            ir.name
        )));
    }
    if ir.contract.is_some() {
        return Err(refuse(format!(
            "kernel `{}` contracts, and this back end emits no contraction.\n  Every kernel \
             here walks its space once with one value per element; a contraction needs an \
             inner loop over the contracted axis and a horizontal fold per output,\n  which is \
             a second loop nest and is not built. Not scheduled either -- said plainly rather \
             than deferred to a step that does not exist.",
            ir.name
        )));
    }
    if let Some(r) = &ir.reduction {
        // The path is the machine's answer, and this machine's is the short one: a tree over
        // the eight lanes of one register is staged nowhere, because `VFREDUCE` folds it in
        // place. ADR-0025 step 3 opened the language to both shapes for exactly this.
        if r.path.contains(&Level::Smem) {
            return Err(refuse(format!(
                "kernel `{}` reduces through `smem`, and `unibit` has no shared level.\n  Here \
                 the parallelism is the eight lanes of one register and the tree is \
                 register-internal, so the path is `reg -> dram`.\n  Declare that for this \
                 target.",
                ir.name
            )));
        }
    }
    if let Some(space) = &ir.space {
        if space.vars.len() > 2 {
            return Err(refuse(format!(
                "kernel `{}` walks a rank-{} space; this back end emits rank 1 and rank 2.",
                ir.name,
                space.vars.len()
            )));
        }
        // A rank-2 space whose buffers are all read at `[i, j]` is a linear walk over
        // `rows * cols` elements, so it is the rank-1 loop with a larger bound and the emitter
        // never needs the two extents apart. That is why `n` stays one number here.
        //
        // A **permuted** one is not, and cannot be emitted on this machine at all: `b[j, i]`
        // puts consecutive `j` at a stride of `rows` in `b`, and the only vector store is
        // `SQ`, which writes 32 contiguous bytes. There is no strided store, no scatter, and
        // no lane extract. `LW`/`SW` could copy it a word at a time, and that is refused too:
        // it moves 4 bytes per instruction where the cost model derived 32, so the ceiling
        // ADR-0022 computes would be eight times the machine.
        if let Some(st) = ir
            .streams
            .iter()
            .find(|st| !st.index.is_empty() && st.index != space.vars)
        {
            return Err(refuse(format!(
                "`{}` is accessed at `[{}]` where the space is `[{}]`, and `unibit` has no \
                 strided or scattered vector store.\n  `SQ` writes eight contiguous f32 and \
                 there is no lane extract, so a permuted axis cannot be emitted -- not slowly, \
                 at all.\n  Refused rather than lowered to a word-at-a-time loop, which would \
                 move 4 bytes per instruction where the cost model derived 32.",
                st.buffer,
                st.index.join(", "),
                space.vars.join(", ")
            )));
        }
    }
    if !n.is_multiple_of(LANES) {
        return Err(refuse(format!(
            "n = {n} is not a multiple of {LANES}.\n  One 256-bit register holds {LANES} f32 \
             and this back end emits no tail loop, so a ragged n would silently compute fewer \
             elements than asked for.\n  Refused rather than rounded."
        )));
    }
    if let Some(p) = ir
        .params
        .iter()
        .find(|p| p.ty == Ty::BufF16 || p.ty == Ty::BufBF16)
    {
        return Err(refuse(format!(
            "`{}` is a narrow buffer and `unibit`'s float unit is packed single precision only \
             (ADR-0025 step 0): there is no `cvt.f32.f16`.\n  Refused rather than emitted as \
             f32, which would move twice the bytes the cost model derived.",
            p.name
        )));
    }
    Ok(())
}

fn emit_data(ir: &KernelIr, prog: &Program, out: &mut String) {
    let n = prog.n;
    let _ = writeln!(out, "        .data");
    for p in &ir.params {
        if !p.ty.is_buffer() {
            continue;
        }
        let words: Vec<String> = lyth_lang::inputs::buffer(&p.name, p.ty, n)
            .iter()
            .map(|v| format!("0x{:08X}", v.to_bits()))
            .collect();
        // One `.word` directive per buffer, never several. Two directives under one label do
        // not land contiguously in this assembler, and `LQ` then reads the end of one buffer
        // followed by the start of whatever sits next -- which assembles, runs, and prints
        // numbers. Found writing `Unibit/programs/saxpy_f32.uasm`.
        let _ = writeln!(out, "{:<8}.word {}", format!("{}:", p.name), words.join(", "));
    }
    // Labels last, and that is placement rather than taste. `.asciiz` advances the data
    // pointer by a byte count that is not a multiple of 32, so a string emitted before the
    // buffers would move every one of them off a register boundary. Put after, they cannot.
    //
    // `PRINT_STRZ` rather than `PRINT_STR`: the latter takes a hand-counted length, and a
    // length counted by hand is one that drifts from the bytes it describes.
    for (i, pr) in prog.prints.iter().enumerate() {
        let _ = writeln!(
            out,
            "{:<8}.asciiz \"{}[{}:{}]\\n\"",
            format!("lbl{i}:"),
            pr.buffer,
            pr.lo,
            pr.hi
        );
    }
    let _ = writeln!(out);
}

fn emit_text(ir: &KernelIr, prog: &Program, out: &mut String) -> Result<(), EmitError> {
    let n = prog.n;
    let _ = writeln!(out, "        .text");
    let _ = writeln!(out, "        .global _start");
    let _ = writeln!(out, "_start:");

    // Buffers the loop *walks*. A reduction's target is not one of them: it receives one value
    // per program, so giving it a base pointer that advances 32 bytes an iteration would march
    // it off the end of a buffer declared `[f32; blocks]`.
    let reduce_into = ir.reduction.as_ref().map(|r| r.into.as_str());
    let buffers: Vec<&str> = ir
        .params
        .iter()
        .filter(|p| p.ty.is_buffer())
        .map(|p| p.name.as_str())
        .filter(|b| Some(*b) != reduce_into)
        .collect();
    if buffers.len() > 8 {
        return Err(refuse(format!(
            "kernel `{}` has {} buffers; this back end keeps one base pointer per saved \
             register, s0 through s7.",
            ir.name,
            buffers.len()
        )));
    }
    for (i, b) in buffers.iter().enumerate() {
        let _ = writeln!(out, "        la      s{i}, {b}");
    }

    let mut next_t = 0usize;
    let mut alloc = |out: &mut String| -> Result<String, EmitError> {
        // t0..t6 are the seven temporaries this ISA names. Running out is a real limit and is
        // reported as one rather than wrapping around and corrupting a live value.
        if next_t >= 7 {
            return Err(refuse(
                "the body needs more than seven live values and this back end does not spill. \
                 A longer expression is a real limit here, not a bug.",
            ));
        }
        let r = format!("t{next_t}");
        next_t += 1;
        let _ = out;
        Ok(r)
    };

    // Scalars, broadcast once before the loop. `VSPLAT.w` copies the low 32 bits into all
    // eight lanes, and an f32 is bits, so the integer instruction serves a float unchanged.
    let mut scalar_reg: Vec<(String, String)> = Vec::new();
    for p in &ir.params {
        if p.ty != Ty::F32 {
            continue;
        }
        // From the program, not from a default. A `main` that says `a = 2.0` and a back end
        // that emits its own 2.0 agree until the day the file says 3.
        let v = *prog.scalars.get(&p.name).ok_or_else(|| {
            refuse(format!(
                "`{}` has no value. A scalar the program does not give is a number this file \
                 would have to invent.",
                p.name
            ))
        })?;
        let r = alloc(out)?;
        let _ = writeln!(
            out,
            "        li      {r}, 0x{:08X}   ; {} = {v}",
            v.to_bits(),
            p.name
        );
        let _ = writeln!(out, "        vsplat.w {r}, {r}");
        scalar_reg.push((p.name.clone(), r));
    }

    // The reduction's accumulator: one running partial **per lane**, live across the whole
    // loop and folded once at the end.
    //
    // That is not a shape this back end chose. It is what `eval_with_launch(ir, n, ., 1, 8)`
    // already describes: grid 1, block 8, so thread `t` folds elements `t, t+8, t+16, ...` in
    // sequence and a tree combines the eight. Lane `l` of this register is thread `t = l`, and
    // the stride is `grid * block = 8` because that is how many f32 one `LQ` brings in. The
    // host oracle for this machine needed no new code, which is the strongest evidence that
    // the launch shape of a Unibit program is a real launch shape and not a metaphor.
    let acc = match &ir.reduction {
        Some(r) => {
            let a = alloc(out)?;
            let _ = writeln!(
                out,
                "        li      {a}, 0x{:08X}   ; {} identity",
                r.op.identity().to_bits(),
                r.op.name()
            );
            let _ = writeln!(out, "        vsplat.w {a}, {a}");
            Some(a)
        }
        None => None,
    };

    let iters = n / LANES;
    let _ = writeln!(out, "        li      s8, {iters}");
    let _ = writeln!(out, "loop:");

    let mut regs: Vec<(RegId, String)> = Vec::new();
    fn get(regs: &[(RegId, String)], id: RegId) -> String {
        regs.iter()
            .find(|(i, _)| *i == id)
            .map(|(_, r)| r.clone())
            .expect("SSA: every use follows its definition")
    }

    for op in &ir.ops {
        match op {
            Op::Load { dst, buffer } => {
                let i = buffers
                    .iter()
                    .position(|b| b == buffer)
                    .expect("a streamed buffer is a parameter");
                let r = alloc(out)?;
                let _ = writeln!(out, "        lq      {r}, 0(s{i})");
                regs.push((*dst, r));
            }
            Op::Param { dst, name } => {
                let r = scalar_reg
                    .iter()
                    .find(|(n, _)| n == name)
                    .map(|(_, r)| r.clone())
                    .ok_or_else(|| refuse(format!("`{name}` is not a broadcast scalar")))?;
                regs.push((*dst, r));
            }
            Op::Const { dst, value } => {
                let r = alloc(out)?;
                let _ = writeln!(
                    out,
                    "        li      {r}, 0x{:08X}",
                    (*value as f32).to_bits()
                );
                let _ = writeln!(out, "        vsplat.w {r}, {r}");
                regs.push((*dst, r));
            }
            Op::Bin { dst, op, lhs, rhs } => {
                let m = match op {
                    BinOp::Add => "vfadd",
                    BinOp::Sub => "vfsub",
                    BinOp::Mul => "vfmul",
                    // The one form of choosing this machine can do without a branch, and the
                    // reason `max` is allowed in a body at all (ADR-0027).
                    BinOp::Max => "vfmax",
                    BinOp::Min => "vfmin",
                    BinOp::Div => {
                        return Err(refuse(
                            "this machine has no packed float divide. ADR-0025 step 0 added \
                             add, sub, mul, fma, max and min, and a divide is not among them.",
                        ))
                    }
                };
                let (l, r2) = (get(&regs, *lhs), get(&regs, *rhs));
                let r = alloc(out)?;
                let _ = writeln!(out, "        {m}   {r}, {l}, {r2}");
                regs.push((*dst, r));
            }
            Op::Fma { dst, a, b, c } => {
                // `VFMA` accumulates into `rd`, so the addend has to be there before the
                // instruction runs. Copying rather than writing into `c`'s register keeps SSA
                // intact: `c` may be read again later in the body.
                let (ra, rb, rc) = (get(&regs, *a), get(&regs, *b), get(&regs, *c));
                let r = alloc(out)?;
                let _ = writeln!(out, "        mv      {r}, {rc}");
                let _ = writeln!(out, "        vfma    {r}, {ra}, {rb}");
                regs.push((*dst, r));
            }
            Op::Neg { dst, src } => {
                // No packed float negate either. `0 - x` is exact, and it is said out loud
                // because a reader counting instructions should know where the extra two came
                // from.
                let s = get(&regs, *src);
                let z = alloc(out)?;
                let r = alloc(out)?;
                let _ = writeln!(out, "        li      {z}, 0");
                let _ = writeln!(out, "        vsplat.w {z}, {z}");
                let _ = writeln!(out, "        vfsub   {r}, {z}, {s}");
                regs.push((*dst, r));
            }
        }
    }

    // Fold this iteration's eight values into the eight running partials.
    //
    // `combine(acc, value)`, in that order, because `eval` writes
    // `acc = r.op.combine(acc, reduced[i])`. It makes no difference to `sum` and it makes one
    // to `max` and `min` when an operand is NaN, and an oracle that agrees for a reason the
    // operator happens to supply is one operator away from disagreeing silently (ADR-0013).
    if let (Some(r), Some(a)) = (&ir.reduction, &acc) {
        let m = match r.op {
            ReduceOp::Sum => "vfadd",
            ReduceOp::Max => "vfmax",
            ReduceOp::Min => "vfmin",
        };
        let v = get(&regs, r.value);
        let _ = writeln!(out, "        {m}   {a}, {a}, {v}");
    }

    for (buffer, src) in &ir.drains {
        let i = buffers
            .iter()
            .position(|b| b == buffer)
            .expect("a drained buffer is a parameter");
        let _ = writeln!(out, "        sq      {}, 0(s{i})", get(&regs, *src));
    }

    for (i, _) in buffers.iter().enumerate() {
        let _ = writeln!(out, "        addi    s{i}, s{i}, 32");
    }
    let _ = writeln!(out, "        addi    s8, s8, -1");
    let _ = writeln!(out, "        bne     s8, zero, loop");

    // The tree, and then the one store that leaves. `VFREDUCE` is specified as stride 4, then
    // 2, then 1 -- the same tree `eval`'s `tree_reduce` walks -- because float addition is not
    // associative and a chain would give a different bit pattern over the same eight lanes.
    //
    // `SW` stores lane 0 alone, four bytes. A `SQ` here would write 32 and clobber seven
    // neighbours of a buffer that holds one result per block.
    if let (Some(r), Some(a)) = (&ir.reduction, &acc) {
        let _ = writeln!(out, "        vfreduce {a}, {a}");
        let _ = writeln!(out, "        la      s10, {}", r.into);
        let _ = writeln!(out, "        sw      {a}, 0(s10)");
    }

    // What leaves the machine.
    //
    // Read back from **memory**, element by element, rather than printed out of the register
    // that computed it: a register dump would pass even if the store had gone to the wrong
    // address, which is precisely the thing a store can get wrong.
    //
    // `PRINT_F32` and not `PRINT_REG256`. The dump is four 64-bit lanes of hex, in an order a
    // reader has to decode, and a program whose output nobody can read is not a program
    // anybody runs. `PRINT_F32` prints the shortest string that parses back to the same bits,
    // so this stays a bit-exact comparison as well as a legible one.
    for (i, pr) in prog.prints.iter().enumerate() {
        let count = pr.hi - pr.lo;
        if count == 0 {
            continue;
        }
        let _ = writeln!(out, "        la      a0, lbl{i}");
        let _ = writeln!(out, "        li      a7, 6          ; print_strz");
        let _ = writeln!(out, "        ecall");
        let _ = writeln!(out, "        la      s10, {}", pr.buffer);
        let _ = writeln!(out, "        addi    s10, s10, {}", pr.lo * 4);
        let _ = writeln!(out, "        li      s11, {count}");
        let _ = writeln!(out, "print{i}:");
        // `LW` sign-extends into 64 bits and the syscall truncates back to 32, so the sign of
        // the f32's top bit never reaches the value that is printed.
        let _ = writeln!(out, "        lw      a0, 0(s10)");
        let _ = writeln!(out, "        li      a7, 7          ; print_f32");
        let _ = writeln!(out, "        ecall");
        let _ = writeln!(out, "        li      a0, 10         ; newline");
        let _ = writeln!(out, "        li      a7, 2          ; print_char");
        let _ = writeln!(out, "        ecall");
        let _ = writeln!(out, "        addi    s10, s10, 4");
        let _ = writeln!(out, "        addi    s11, s11, -1");
        let _ = writeln!(out, "        bne     s11, zero, print{i}");
    }

    let _ = writeln!(out, "        halt");
    Ok(())
}
