/* GENERATED BY LYTH from saxpy.lyth. Do not edit. */
/*
 * Contract: 0.1667 flop/byte derived on sm_120, 2 flop and 12 byte per element.
 *
 * Define LYTH_SAXPY_IMPLEMENTATION in one translation unit for the bodies.
 * Needs the CUDA driver API only: compile with cuda.h and link cuda.
 */
#ifndef LYTH_SAXPY_H
#define LYTH_SAXPY_H

#include <cuda.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LYTH_SAXPY_KERNEL "saxpy"
#define LYTH_SAXPY_MACHINE "sm_120"
#define LYTH_SAXPY_BLOCK 256u
#define LYTH_SAXPY_SHARED_BYTES 0u
#define LYTH_SAXPY_MAX_GRID 1048576u

/* The cost model, so a caller can assert on it without a profiler. */
#define LYTH_SAXPY_DERIVED_INTENSITY 0.16666666666666666
#define LYTH_SAXPY_FLOPS_PER_ELEMENT 2.0
#define LYTH_SAXPY_BYTES_PER_ELEMENT 12.0
#define LYTH_SAXPY_COALESCENCE 1.0

/* Elements the kernel walks. 0 means the extents overflow a 32-bit index. */
unsigned int lyth_saxpy_elements(unsigned int n);
/* Blocks the default launch uses: one element per thread, capped. 0 on overflow. */
unsigned int lyth_saxpy_grid(unsigned int n);
/* The kernel writes: y. Every other buffer it only reads. C cannot say this in the
   signature -- CUdeviceptr is an integer handle -- so it is said here. */
/* Load the embedded PTX. The module must outlive every launch. */
CUresult lyth_saxpy_load(CUmodule *module, CUfunction *fn);
CUresult lyth_saxpy_launch(CUfunction fn, unsigned int n, float a, CUdeviceptr x, CUdeviceptr y);
CUresult lyth_saxpy_launch_with(CUfunction fn, unsigned int grid, unsigned int n, float a, CUdeviceptr x, CUdeviceptr y);

#ifdef __cplusplus
}
#endif

#ifdef LYTH_SAXPY_IMPLEMENTATION

static const char lyth_saxpy_ptx[] =
    "//\n"
    "// Generated by LYTH. Do not edit.\n"
    "//   kernel    saxpy\n"
    "//   machine   sm_120\n"
    "//   derived   0.166667 flop/byte = 2 flop / 12 byte per element\n"
    "//   traffic   8 read + 4 written, per element, at dram\n"
    "//\n"
    ".version 8.7\n"
    ".target sm_120\n"
    ".address_size 64\n"
    "\n"
    ".visible .entry saxpy(\n"
    "    .param .u32 saxpy_n,\n"
    "    .param .f32 saxpy_a,\n"
    "    .param .u64 saxpy_x,\n"
    "    .param .u64 saxpy_y\n"
    ")\n"
    "{\n"
    "    .reg .pred  %p<2>;\n"
    "    .reg .f32   %f<5>;\n"
    "    .reg .b32   %r<8>;\n"
    "    .reg .b64   %rd<8>;\n"
    "\n"
    "    ld.param.u32 %r1, [saxpy_n];\n"
    "    ld.param.f32 %f1, [saxpy_a];\n"
    "    ld.param.u64 %rd1, [saxpy_x];\n"
    "    cvta.to.global.u64 %rd2, %rd1;\n"
    "    ld.param.u64 %rd3, [saxpy_y];\n"
    "    cvta.to.global.u64 %rd4, %rd3;\n"
    "    mov.u32 %r2, %ctaid.x;\n"
    "    mov.u32 %r3, %ntid.x;\n"
    "    mov.u32 %r4, %tid.x;\n"
    "    mov.u32 %r5, %nctaid.x;\n"
    "    mad.lo.s32 %r6, %r2, %r3, %r4;\n"
    "    mul.lo.s32 %r7, %r5, %r3;\n"
    "$L_loop_saxpy:\n"
    "    setp.ge.u32 %p1, %r6, %r1;\n"
    "    @%p1 bra $L_loop_end_saxpy;\n"
    "    mul.wide.u32 %rd5, %r6, 4;\n"
    "    add.s64 %rd6, %rd2, %rd5;\n"
    "    add.s64 %rd7, %rd4, %rd5;\n"
    "    ld.global.f32 %f2, [%rd6];\n"
    "    ld.global.f32 %f3, [%rd7];\n"
    "    fma.rn.f32 %f4, %f1, %f2, %f3;\n"
    "    st.global.f32 [%rd7], %f4;\n"
    "    add.s32 %r6, %r6, %r7;\n"
    "    bra $L_loop_saxpy;\n"
    "$L_loop_end_saxpy:\n"
    "$L_done_saxpy:\n"
    "    ret;\n"
    "}\n"
;

unsigned int lyth_saxpy_elements(unsigned int n)
{
    return n;
}

unsigned int lyth_saxpy_grid(unsigned int n)
{
    unsigned int total = lyth_saxpy_elements(n);
    unsigned int g;
    if (total == 0u) return 0u;
    g = (total + LYTH_SAXPY_BLOCK - 1u) / LYTH_SAXPY_BLOCK;
    if (g == 0u) g = 1u;
    if (g > LYTH_SAXPY_MAX_GRID) g = LYTH_SAXPY_MAX_GRID;
    return g;
}

CUresult lyth_saxpy_load(CUmodule *module, CUfunction *fn)
{
    CUresult r = cuModuleLoadData(module, lyth_saxpy_ptx);
    if (r != CUDA_SUCCESS) return r;
    return cuModuleGetFunction(fn, *module, LYTH_SAXPY_KERNEL);
}

CUresult lyth_saxpy_launch_with(CUfunction fn, unsigned int grid, unsigned int n, float a, CUdeviceptr x, CUdeviceptr y)
{
    void *args[] = { (void *)&n, (void *)&a, (void *)&x, (void *)&y };
    return cuLaunchKernel(fn, grid, 1, 1, LYTH_SAXPY_BLOCK, 1, 1,
                          LYTH_SAXPY_SHARED_BYTES, 0, args, 0);
}

CUresult lyth_saxpy_launch(CUfunction fn, unsigned int n, float a, CUdeviceptr x, CUdeviceptr y)
{
    unsigned int grid = lyth_saxpy_grid(n);
    if (grid == 0u) return CUDA_ERROR_INVALID_VALUE;
    return lyth_saxpy_launch_with(fn, grid, n, a, x, y);
}

#endif /* LYTH_SAXPY_IMPLEMENTATION */
#endif /* LYTH_SAXPY_H */
